gems/devise/OSVDB-89642.yml, gems/doorkeeper/CVE-2014-8144.yml, gems/dragonfly/OSVDB-90647.yml, gems/sentry-raven/OSVDB-115654.yml, gems/sprockets/CVE-2014-7819.yml, gems/webbynode/OSVDB-100920.yml, gems/wicked/OSVDB-98270.yml
Nothing big, just an update for given advisories.
=> Update of several advisories

gems/ruby-saml/OSVDB-117903.yml
https://github.com/onelogin/ruby-saml/blob/master/changelog.md#082-jan-26-2015
=> Add ruby-saml Gem advisory

gems/rest-client/OSVDB-117461.yml
This issue was addressed in 1.7.3
=> Update rest-client entry to reflect patch.

gems/doorkeeper/OSVDB-118830.yml
Maybe someone can double check if the 'patched_versions' fits.
https://github.com/doorkeeper-gem/doorkeeper/issues/576
https://github.com/doorkeeper-gem/doorkeeper/blob/master/CHANGELOG.md#212
=> Add Doorkeeper ruby gem advisory

gems/doorkeeper/OSVDB-118830.yml, gems/dragonfly/OSVDB-90647.yml
The `.com` is a parked domain :tada:
=> Link to correct OSVDB website

gems/doorkeeper/OSVDB-118830.yml
The fixes for 118830 have been backported to v1.4.2
Relevant change: https://github.com/doorkeeper-gem/doorkeeper/commit/457d9d4ce084b511594448ff25f6a2b84f9a7b8a
=> Add patched version Doorkeeper v1.4.2 [118830]

gems/xaviershay-dm-rails/OSVDB-118579.yml
I just added xaviershay-dm-rails cause of the osvdb entry.
POC: http://www.vapid.dhs.org/advisory.php?v=115
@xaviershay FYI
=> Add xaviershay-dm-rails Gem advisory

gems/kompanee-recipes/OSVDB-108593.yml
Just added it cause of an older osvdb entry...for the sake of completeness.
https://rubygems.org/gems/kompanee-recipes
http://osvdb.org/show/osvdb/108593
http://www.vapid.dhs.org/advisory.php?v=67
=> Add Ruby kompanee-recipes Gem advisory

gems/rest-client/CVE-2015-1820.yml
https://github.com/rest-client/rest-client/issues/369
=> Add rest-client CVE-2015-1820.

gems/arabic-prawn/OSVDB-104365.yml, gems/backup_checksum/OSVDB-108569.yml, gems/curl/OSVDB-91230.yml, gems/echor/OSVDB-102129.yml, gems/echor/OSVDB-102130.yml, gems/kajam/OSVDB-108529.yml, gems/rest-client/CVE-2015-1820.yml, gems/sentry-raven/OSVDB-115654.yml
=> Update Gems with CVE numbers

gems/fat_free_crm/OSVDB-101445.yml, gems/fat_free_crm/OSVDB-101446.yml, gems/fat_free_crm/OSVDB-101447.yml, gems/fat_free_crm/OSVDB-101448.yml, gems/fat_free_crm/OSVDB-101700.yml, gems/fat_free_crm/OSVDB-110420.yml, gems/fat_free_crm/OSVDB-118465.yml
=> Add Fat Free CRM Ruby Gem advisories

gems/redcarpet/OSVDB-120415.yml
http://osvdb.org/show/osvdb/120415
=> Add redcarpet Ruby Gem advisory

gems/refile/OSVDB-120857.yml
=> Add refile Ruby Gem

gems/rest-client/OSVDB-117461.yml
Just adding in the CVE number for a previously reported item.
=> Add rest-client vuln CVE number

gems/open-uri-cached/OSVDB-121701.yml
Didn't found a poc or any other additional information.
=> Add open-uri-cached ruby gem

gems/bson/CVE-2015-4412.yml, gems/moped/CVE-2015-4410.yml
@postmodern 
I added a `vendor_patch` attribute. Let me know if you disagree. I was stuck between `vendor_uri` or `vendor_context`.
Also, @durran and @estolfo, sorry for the extra work but - the purpose of these files is to ensure people can upgrade to safe versions. 
Could you confirm if the version information is correct?
Much obliged,
=> Added bson, moped data injection CVE-2015-441{0,2}

gems/activesupport/CVE-2015-3226.yml, gems/activesupport/CVE-2015-3227.yml, gems/jquery-rails/CVE-2015-1840.yml, gems/rack/CVE-2015-3225.yml, gems/web-console/CVE-2015-3224.yml
@skorth @mveytsman pls review <3
=> Added activesupport, jquery-rails, rack, web-console disclosures.

gems/paperclip/CVE-2015-2963.yml
https://robots.thoughtbot.com/paperclip-security-release
https://github.com/thoughtbot/paperclip/commit/9aee4112f36058cd28d5fe4a006d6981bd1eda57
https://jvn.jp/en/jp/JVN83881261/index.html
=> Adding CVE-2015-2963

gems/bcrypt-ruby/OSVDB-62067.yml
http://www.mindrot.org/files/jBCrypt/internat.adv
https://github.com/codahale/bcrypt-ruby/commit/92c8e4e3760d089e494b7a3ac1faa563681868c7
Fixes #34.
=> Adding OSVDB-62067

gems/redcarpet/CVE-2015-5147.yml, gems/redcarpet/OSVDB-120415.yml
http://seclists.org/oss-sec/2015/q2/818
https://github.com/vmg/redcarpet/commit/2cee777c1e5babe8a1e2683d31ea75cc4afe55fb
=> Adding CVE-2015-5147 and fixing date for OSVDB-120415

gems/brbackup/OSVDB-108899.yml, gems/brbackup/OSVDB-108900.yml, gems/brbackup/OSVDB-108901.yml
http://seclists.org/oss-sec/2014/q3/123
=> Adding OSVDB-108899, OSVDB-108900, and OSVDB-108901 for brbackup

gems/rack-ssl/OSVDB-104734.yml
https://github.com/josh/rack-ssl/commit/9d7d7300b907e496db68d89d07fbc2e0df0b487b
https://bugzilla.redhat.com/show_bug.cgi?id=1078612
http://www.openwall.com/lists/oss-security/2014/03/19/2
=> Adding OSVDB-104734 / CVE-2014-2538 for rack-ssl

gems/rack-ssl/OSVDB-104734.yml
See https://github.com/josh/rack-ssl/pull/34 and https://github.com/josh/rack-ssl/compare/v1.3.3...v1.3.4
=> rack-ssl 1.3.4 is also patched for this issue

gems/activerecord-oracle_enhanced-adapter/OSVDB-95376.yml, gems/activerecord/OSVDB-90072.yml, gems/activerecord/OSVDB-90073.yml, gems/activeresource/OSVDB-95749.yml, gems/authlogic/OSVDB-89064.yml, gems/builder/OSVDB-95668.yml, gems/bundler/OSVDB-110004.yml, gems/bundler/OSVDB-115090.yml, gems/bundler/OSVDB-115091.yml, gems/bundler/OSVDB-115917.yml, gems/curb/OSVDB-114600.yml, gems/dragonfly/OSVDB-110439.yml, gems/dragonfly/OSVDB-90647.yml, gems/dragonfly/OSVDB-97854.yml, gems/fog-dragonfly/OSVDB-96798.yml, gems/json/OSVDB-101137.yml, gems/json/OSVDB-101157.yml, gems/json/OSVDB-90074.yml
Went through http://osvdb.org/search?kthx=search&page=1&search[referencetypes]=&search[refid]=&search[text_type]=titles&search[vuln_title]=gem (all 3 pages) to make sure we were tracking all the ruby gems... Still needs another run through once all my PRs have been merged.
=> More auditing of ruby gem OSVDB reports to ensure we are tracking all of them

.gitignore, .travis.yml, Gemfile, scripts/post-advisories.sh
Update advisories on rubysec website every time a successful commit
is made on the master branch.
Fixes #160.
=> Add Travis CI support for automagically updating rubysec website

gems/actionpack/CVE-2014-7829.yml
Hopefully I'm doing this right.
=> Update CVE-2014-7829 with unaffected versions

gems/sidekiq/OSVDB-125675.yml, gems/sidekiq/OSVDB-125676.yml, gems/sidekiq/OSVDB-125677.yml, gems/sidekiq/OSVDB-125678.yml
=> Add OSVDB-125675, OSVDB-125676, OSVDB-125677, and OSVDB-125678 for sidekiq

rubies/ruby/CVE-2009-5147.yml, rubies/ruby/OSVDB-93414.yml
These didn't make it into my previous change for whatever reason.
=> Add CVE-2009-5147 for Ruby engine and modify affected versions for OSVDB-93414

Rakefile, libraries/rubygems/CVE-2013-4287.yml, libraries/rubygems/CVE-2013-4363.yml, libraries/rubygems/CVE-2015-3900.yml, libraries/rubygems/CVE-2015-4020.yml, libraries/rubygems/OSVDB-33561.yml, libraries/rubygems/OSVDB-81444.yml, libraries/rubygems/OSVDB-85809.yml, spec/gems_spec.rb, spec/library_example.rb
=> Add advisories for Rubygems library

gems/uglifier/OSVDB-126747.yml
https://github.com/mishoo/UglifyJS2/issues/751
https://zyan.scripts.mit.edu/blog/backdooring-js/
=> Adding OSVDB-126747 for uglifier

gems/sidekiq-pro/OSVDB-126329.yml, gems/sidekiq-pro/OSVDB-126330.yml, gems/sidekiq-pro/OSVDB-126331.yml
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
These are for the closed-source `sidekiq-pro` gem (https://github.com/mperham/sidekiq-pro/).
=> Add OSVDB-126329, OSVDB-126330, and OSVDB-126331 for sidekiq-pro

gems/devise-two-factor/CVE-2015-7225.yml
Awaiting identifier from OSVDB.
Was just assigned the CVE identifier, so it's not on MITRE's site yet.
=> Add CVE-2015-7225 to devise-two-factor

gems/gollum-grit_adapter/CVE-2014-9489.yml
https://github.com/gollum/gollum/issues/913
https://github.com/gollum/grit_adapter/commit/4520d973c81fecfebbeacd2ef2f1849d763951c7
=> Add CVE-2014-9489 for gollum-grit_adapter

gems/gollum/CVE-2015-7314.yml
http://seclists.org/oss-sec/2015/q3/594
https://github.com/gollum/gollum/pull/1069
https://github.com/gollum/gollum/commit/ce68a88293ce3b18c261312392ad33a88bb69ea1
=> Add CVE-2015-7314 for gollum

gems/gollum/CVE-2015-7314.yml
=> Add OSVDB-127779 reference to CVE-2015-7314 for gollum

gems/passenger/CVE-2015-7519.yml
It has been a long time since my last commit. Please double check.
=> Add passenger ruby gem (CVE-2015-7519)

gems/handlebars-source/OSVDB-131671.yml, gems/mustache-js-rails/OSVDB-131671.yml
=> Add OSVDB-131671 for handlebars-source and mustache-js-rails ruby gems

gems/mail/OSVDB-131677.yml
=> Add OSVDB-131677 for mail ruby gem

rubies/ruby/2015-7551.yml, rubies/ruby/CVE-2015-7551.yml
=> Add CVE-2015-7551 for ruby engine

gems/colorscore/CVE-2015-7541.yml
http://seclists.org/oss-sec/2016/q1/17
=> Add CVE-2015-7541 for colorscore

gems/rack-attack/OSVDB-132234.yml
https://github.com/kickstarter/rack-attack/releases/tag/v4.3.1
https://github.com/kickstarter/rack-attack/commit/76c2e3143099d938883ae5654527b47e9e6a8977
=> Add OSVDB-132234 for rack-attack

CONTRIBUTORS.md
Seriously though, I hope you don’t mind me adding him! He’s added way
more stuff than I have! He deserves it! ;P
=> How was Reed not already on the Contributors list?

gems/auto_awesomplete/OSVDB-132800.yml, gems/auto_select2/OSVDB-132800.yml
I thought about creating an Issue instead of a PR cause i am not 100% sure if this security fix is worth it. There is no CVE/OSVDB, so i just played around with the numbering system https://github.com/rubysec/ruby-advisory-db/issues/224, too.
=> Add auto_select2 and auto_awesomplete ruby gem

gems/ember-source/CVE-2013-4170.yml, gems/ember-source/CVE-2014-0013.yml, gems/ember-source/CVE-2014-0014.yml, gems/ember-source/CVE-2014-0046.yml, gems/ember-source/CVE-2015-1866.yml, gems/ember-source/CVE-2015-7565.yml
* CVE-2013-4170
* CVE-2014-0013
* CVE-2014-0014
* CVE-2014-0046
* CVE-2015-1866
* CVE-2015-7565
=> Add missing advisories for ember-source

gems/nokogiri/CVE-2015-7499.yml
https://groups.google.com/forum/#!topic/ruby-security-ann/Dy7YiKb_pMM
=> Add CVE-2015-7499 for nokogiri

gems/devise/CVE-2015-8314.yml
http://blog.plataformatec.com.br/2016/01/improve-remember-me-cookie-expiration-in-devise/
https://srcclr.com/security/unauthorized-access-using-remember-me/ruby/s-1927
=> Add CVE-2015-8314 for devise

gems/mapbox-rails/OSVDB-129854.yml, gems/mapbox-rails/OSVDB-132871.yml
WIP -- OSVDB/CVE entries pending
=> Add advisories for mapbox-rails

.gitignore, Gemfile, Gemfile.lock
This fixes #246, which is the reason why the Travis build for #245 is failing.
=> Unlock explicit version of RSpec and add Gemfile.lock

gems/spina/CVE-2015-4619.yml
=> Add Spina Ruby Gem

gems/safemode/CVE-2016-3693.yml
=> Add safemode ruby gem advisory

gems/nokogiri/CVE-2015-8806.yml
=> Add CVE-2015-8806 for nokogiri

CONTRIBUTING.md, README.md, spec/advisory_example.rb
=> Add CVSSv3 to the spec

gems/actionview/CVE-2016-6316.yml, gems/activerecord/CVE-2016-6317.yml
https://groups.google.com/forum/#!topic/rubyonrails-security/I-VWr034ouk
https://groups.google.com/forum/#!topic/rubyonrails-security/rgO20zYW33s
=> Add CVE-2016-6316 for actionview and CVE-2016-6317 for activerecord

CONTRIBUTORS.md, gems/archive-tar-minitar/CVE-2016-10173.yml, gems/minitar/CVE-2016-10173.yml
=> Directory traversal vulns for minitar

gems/git-fastclone/CVE-2015-8968.yml, gems/git-fastclone/CVE-2015-8969.yml
=> Git fastclone vulns

CONTRIBUTORS.md, gems/espeak-ruby/CVE-2016-10193.yml
=> Bcoles espeak ruby

gems/passenger/CVE-2016-10345.yml
I add CVE-2016-10345.yml. 
I used the following articles as a reference when I wrote CVE-2016-10345.yml.
https://blog.phusion.nl/2017/01/10/passenger-5-1-1/
https://access.redhat.com/security/cve/cve-2016-10345
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-10345
=> Add passenger/ CVE-2016-10345.

gems/actionpack/CVE-2015-7576.yml
ref https://nvd.nist.gov/vuln/detail/CVE-2015-7576
=> Added missing severity values for CVE-2015-7576

rubies/ruby/CVE-2017-0898.yml, rubies/ruby/CVE-2017-10784.yml, rubies/ruby/CVE-2017-14033.yml, rubies/ruby/CVE-2017-14064.yml
=> Adds Ruby vulnerabilities

gems/nokogiri/CVE-2017-9050.yml
=> Adds CVE-2017-9050 etc for nogokgiri/libxml2

gems/safemode/CVE-2017-7540.yml
https://nvd.nist.gov/vuln/detail/CVE-2017-7540
=> Add CVE-2017-7504 for safemode

gems/omniauth/CVE-2017-18076.yml
=> Add omniauth CVE-2017-18076. 

gems/ruby-saml/CVE-2017-11428.yml
https://github.com/onelogin/ruby-saml/commit/048a544730930f86e46804387a6b6fad50d8176f
https://duo.com/blog/duo-finds-saml-vulnerabilities-affecting-multiple-implementations
https://www.kb.cert.org/vuls/id/475445
=> Add CVE-2017-11428 for ruby-saml

gems/loofah/CVE-2018-8048.yml
see https://github.com/flavorjones/loofah/issues/144
also announced here: https://groups.google.com/forum/#!topic/rubyonrails-security/b__OeLG9bts
note the affected versions section - should this be included in the description?
=> CVE-2018-8048 - Loofah XSS Vulnerability

gems/sprockets/CVE-2018-3760.yml
As announced in https://groups.google.com/forum/#!topic/ruby-security-ann/2S9Pwz2i16k.
=> Add Path Traversal in Sprockets vulnerability

gems/twitter-bootstrap-rails/OSVDB-109206.yml
=> Fix broken link in CVE-2014-4920

gems/loofah/CVE-2018-16468.yaml
As detailed in https://github.com/flavorjones/loofah/issues/154.
=> Add CVE-2018-16468

gems/rack/CVE-2018-16470.yml
Possible DoS vulnerability in Rack
=> Add CVE-2018-16470

gems/rack/CVE-2018-16471.yml
Possible XSS vulnerability in Rack
=> Add CVE-2018-16471

gems/easymon/CVE-2018-1000855.yml
Here is a CVE for a reflected XSS in `easymon` gem. Let me know if you need anything else!
=> Add CVE-2018-1000855 for easymon

gems/actionview/CVE-2019-5419.yml
=> Add CVE 2019-5419

gems/bootstrap-sass/CVE-2019-8331.yml
Noticed this CVE was not in the database. Let me know if I missed anything. Thanks!
=> Add CVE-2019-8331 for bootstrap-sass

gems/bootstrap-sass/CVE-2016-10735.yml, gems/bootstrap/CVE-2016-10735.yml, gems/bootstrap/CVE-2018-14040.yml
Let me know if these look good. Thanks!
=> Bootstrap multiple vulnerabilities

gems/field_test/CVE-2019-13146.yml
For https://github.com/ankane/field_test/issues/17
=> Added CVE-2019-13146 for field_test

lib/github_advisory_sync.rb
GHSAs are GitHub Security Advisories.  They can be made by maintainers from their repo using the [Security->Advisories beta feature](https://help.github.com/en/articles/about-maintainer-security-advisories) which is quite new.
Previously the sync script would only sync CVE based advisories.  Now it will sync both CVEs and GHSAs too.  It just a required a couple tweaks in how the IDs are accessed when needed.
=> GitHub sync rake task writes ghsa advisories, as well as CVEs

gems/devise/CVE-2019-5421.yml
Source: https://nvd.nist.gov/vuln/detail/CVE-2019-5421
=> Update CVSS score for CVE-2019-5421 devise

gems/loofah/CVE-2019-15587.yml
Details in https://github.com/flavorjones/loofah/issues/171
=> Add CVE-2019-15587 for Loofah

CONTRIBUTING.md, CONTRIBUTORS.md, README.md
When I would like to do my first PR, I occur this kind of errors : 
```shell
Failures:
1) gems spec/../gems/ruby_parser-legacy/CVE-2019-18409.yml date should be a kind of Date
Failure/Error: it { is_expected.to be_kind_of(Date) }
expected nil to be a kind of Date
Shared Example Group: "Advisory" called from ./spec/gem_example.rb:5
Shared Example Group: "Gem Advisory" called from ./spec/advisories_spec.rb:8
2) gems spec/../gems/ruby_parser-legacy/CVE-2019-18409.yml should have valid schema
Failure/Error: expect(errors).to be_empty
expected `[#<Kwalify::ValidationError: [/] key 'date:' is required.>].empty?` to return true, got false
Shared Example Group: "Gem Advisory" called from ./spec/advisories_spec.rb:8
```
So I update the readme to allow copy/past examples.
=> update README and CONTRIBUTING

gems/chartkick/CVE-2019-18841.yml
For https://github.com/ankane/chartkick.js/issues/117
=> Added CVE-2019-18841 for Chartkick

gems/administrate/CVE-2020-5257.yml
https://github.com/thoughtbot/administrate/security/advisories/GHSA-2p5p-m353-833w
=> Add CVE-2020-5257 for administrate gem

gems/doorkeeper/CVE-2020-10187.yml
https://github.com/doorkeeper-gem/doorkeeper/security/advisories/GHSA-j7vx-8mqj-cqp9
=> Add CVE-2020-10187 for doorkeeper

gems/field_test/CVE-2020-16252.yml
For https://github.com/ankane/field_test/issues/28
=> Added CVE-2020-16252 for field_test

gems/chartkick/CVE-2020-16254.yml
For https://github.com/ankane/chartkick/issues/546
=> Added CVE-2020-16254 for chartkick

gems/omniauth/CVE-2015-9284.yml
https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284 is a good summary of the issue.
=> Link to dedicated omniauth page for CVE-2015-9284

gems/trestle-auth/CVE-2021-29435.yml
https://github.com/TrestleAdmin/trestle-auth/security/advisories/GHSA-h8hx-2c5r-32cf
=> Add CVE-2021-29435 for trestle-auth

gems/pgsync/CVE-2021-31671.yml
For https://github.com/ankane/pgsync/issues/121
=> Added CVE-2021-31671 for pgsync

gems/actionpack/CVE-2015-7581.yml, gems/actionpack/CVE-2016-2098.yml, gems/actionpack/CVE-2020-8264.yml, gems/actionpack/CVE-2021-22885.yml, gems/actionview/CVE-2016-2097.yml, gems/actionview/CVE-2019-5418.yml, gems/actionview/CVE-2019-5419.yml, gems/actionview/CVE-2020-5267.yml, gems/activejob/CVE-2018-16476.yml, gems/activerecord/CVE-2016-6317.yml, gems/activestorage/CVE-2018-16477.yml, gems/administrate/CVE-2020-5257.yml, gems/airbrake-ruby/CVE-2019-16060.yml, gems/consul/CVE-2019-16377.yml, gems/devise/CVE-2019-16109.yml, gems/dragonfly/CVE-2021-33564.yml, gems/ember-source/CVE-2015-7565.yml, gems/excon/CVE-2019-16779.yml, gems/field_test/CVE-2019-13146.yml, gems/foreman_fog_proxmox/CVE-2021-20259.yml, gems/pgsync/CVE-2021-31671.yml, gems/rack/CVE-2019-16782.yml, gems/railties/CVE-2019-5420.yml, gems/ruby-saml/CVE-2017-11428.yml, gems/trestle-auth/CVE-2021-29435.yml
Split out the data update from #479 per [comment](https://github.com/rubysec/ruby-advisory-db/pull/479#pullrequestreview-688488269)
=> update vulnerabilities with cvss_v3 from github

gems/blazer/CVE-2022-29498.yml
For https://github.com/ankane/blazer/issues/392
=> Added CVE-2022-29498 for blazer

gems/ruby-mysql/CVE-2021-32740.yml
Fix #507 by adding advisory for CVE-2021-3270
=> Add CVE-2021-3270 for ruby-mysql

README.md
=> docs: fix broken link for OSVDB

gems/nokogiri/GHSA-qv4q-mr5r-qprj.yml
See https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-qv4q-mr5r-qprj
=> Add GHSA-qv4q-mr5r-qprj for nokogiri

gems/loofah/CVE-2022-23514.yml, gems/loofah/CVE-2022-23515.yml, gems/loofah/CVE-2022-23516.yml, gems/rails-html-sanitizer/CVE-2022-23517.yml, gems/rails-html-sanitizer/CVE-2022-23518.yml, gems/rails-html-sanitizer/CVE-2022-23519.yml, gems/rails-html-sanitizer/CVE-2022-23520.yml
This morning's GHSAs and CVEs for loofah and rails-html-sanitizer.
=> add CVEs for loofah and rails-html-sanitizer

gems/pghero/CVE-2023-22626.yml
For https://github.com/ankane/pghero/issues/439
=> Added CVE-2023-22626 for pghero

gems/clockwork_web/CVE-2023-25015.yml
For https://github.com/ankane/clockwork_web/issues/4
=> Added CVE-2023-25015 for clockwork_web

rubies/ruby/CVE-2017-17790.yml
See if I have fixed my branching issues.
Adding a single file, rubies/ruby/CVE-2017-17790.yml file.
It is related to issue #438.
Feel free to edit the file. Some of the text came from the GHSA database.
=> Added rubies/ruby/CVE-2017-17790.yml

CONTRIBUTORS.md, gems/uri/CVE-2023-28755.yml
Added the YAML file for the CVE 2023-28755. Please let me know if you need me to make any changes :)
=> Add gems/uri/CVE-2023-28755.yml

gems/nokogiri/GHSA-pxvg-2qj5-37jq.yml
See https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-pxvg-2qj5-37jq
=> Add gems/nokogiri/GHSA-pxvg-2qj5-37jq.yml

gems/actionpack/CVE-2011-3186.yml, gems/gtk2/CVE-2007-6183.yml, gems/jruby-openssl/CVE-2009-4123.yml, gems/mail/CVE-2011-0739.yml, gems/rack/CVE-2011-5036.yml, gems/rubygems-update/CVE-2007-0469.yml, gems/spree/CVE-2008-7310.yml, gems/spree/CVE-2008-7311.yml, gems/spree/CVE-2010-3978.yml
9 modified files from github_advisory_sync.rb script
* Straight from github_advisory_sync.rb script.
* Then I manually reviewed them and fixes title/description fields (tried to be consistent).
* Ran "yamllint" (fixes issues).
* Ran "rake" (clean).
=> 9 modified files from github_advisory_sync.rb script

gems/actionpack/CVE-2012-1099.yml, gems/actionpack/CVE-2012-3424.yml, gems/actionpack/CVE-2012-3463.yml, gems/actionpack/CVE-2012-3465.yml, gems/activerecord/CVE-2012-2661.yml, gems/activerecord/CVE-2012-6496.yml, gems/activesupport/CVE-2012-1098.yml, gems/activesupport/CVE-2012-3464.yml, gems/authlogic/CVE-2012-6497.yml, gems/ldap_fluff/CVE-2012-5604.yml, gems/mail/CVE-2012-2139.yml, gems/mail/CVE-2012-2140.yml, gems/nokogiri/CVE-2012-6685.yml, gems/omniauth-oauth2/CVE-2012-6134.yml, gems/passenger/CVE-2012-6135.yml, gems/rack-cache/CVE-2012-2671.yml, gems/rack/CVE-2012-6109.yml
17 modified (2012) files from github_advisory_sync.rb script
Straight from github_advisory_sync.rb script.
Then I manually reviewed them and fixes title/description fields (tried to be consistent).
Ran "yamllint" (fixes issues).
Ran "rake" (clean).
=> 17 modified files from github_advisory_sync.rb script

gems/actionmailer/CVE-2013-4389.yml, gems/actionpack/CVE-2013-0156.yml, gems/actionpack/CVE-2013-1855.yml, gems/actionpack/CVE-2013-1857.yml, gems/actionpack/CVE-2013-4491.yml, gems/actionpack/CVE-2013-6414.yml, gems/actionpack/CVE-2013-6415.yml, gems/actionpack/CVE-2013-6416.yml, gems/actionpack/CVE-2013-6417.yml, gems/activerecord/CVE-2013-0155.yml, gems/activerecord/CVE-2013-0276.yml, gems/activerecord/CVE-2013-0277.yml, gems/activerecord/CVE-2013-1854.yml, gems/activesupport/CVE-2013-0333.yml, gems/activesupport/CVE-2013-1856.yml, gems/aescrypt/CVE-2013-7463.yml, gems/bio-basespace-sdk/CVE-2013-7111.yml, gems/bundler/CVE-2013-0334.yml, gems/cocaine/CVE-2013-4457.yml, gems/command_wrap/CVE-2013-1875.yml, gems/crack/CVE-2013-1800.yml, gems/cremefraiche/CVE-2013-2090.yml, gems/curl/CVE-2013-2617.yml
23 modified (2013) files from github_advisory_sync.rb script
Straight from github_advisory_sync.rb script.
Then I manually reviewed them and fixes title/description fields (tried to be consistent).
Ran "yamllint" (fixes issues).
Ran "rake" (clean).
This is 1st set of 3 modified 2013 files.
=> 23 modified files from github_advisory_sync.rb script

CONTRIBUTING.md, README.md, spec/schemas/ruby.yml
1. Sync'ed README and CONTRIBUTING text.
2. Added mruby spec overhead code
=> Sync'ed README and CONTRIBUTING text; Added mruby spec overhead code

gems/metasploit-framework/CVE-2020-7385.yml, gems/rubygems-update/CVE-2015-4020.yml, gems/sidekiq/CVE-2023-1892.yml
GHSA current sync script + manual again (1 new and 2 modified)
yamllint and rake (green)
=> GHSA current sync script + manual again (1 new and 2 modified)

gems/actionpack/CVE-2011-0447.yml, gems/actionpack/CVE-2011-0449.yml, gems/actionpack/CVE-2011-1497.yml, gems/actionpack/CVE-2011-2197.yml, gems/actionpack/CVE-2011-2929.yml, gems/actionpack/CVE-2011-2931.yml, gems/actionpack/CVE-2011-3187.yml, gems/actionpack/CVE-2011-4319.yml, gems/actionview/CVE-2011-0446.yml, gems/activerecord/CVE-2010-3933.yml, gems/activerecord/CVE-2011-0448.yml, gems/activerecord/CVE-2011-2930.yml, gems/activesupport/CVE-2011-2197.yml, gems/activesupport/CVE-2011-2932.yml, gems/sqlite3-ruby/CVE-2011-0995.yml, gems/thin/CVE-2009-3287.yml
2 modified + 14 new GHSA-based 2009 and 2011 advisories
yamllint and rake (green)
=> 2 modified + 14 new GHSA-based 2009 and 2011 advisories

gems/CVE-2012-3865.yml, gems/actionpack/CVE-2012-2660.yml, gems/actionpack/CVE-2012-2694.yml, gems/activerecord/CVE-2012-2695.yml, gems/activesupport/CVE-2011-2932.yml, gems/puppet/CVE-2012-1989.yml, gems/puppet/CVE-2012-3408.yml, gems/puppet/CVE-2012-3866.yml, gems/puppet/CVE-2012-3867.yml, gems/redcloth/CVE-2012-6684.yml, gems/rubygems-update/CVE-2012-2125.yml, gems/rubygems-update/CVE-2012-2126.yml
3 modified and 9 new GHSA-based 2011/2012 advisories
yamllint and rake (green)
=> 3 modified and 9 new 2011/2012 advisories

gems/puppet/CVE-2012-3865.yml, gems/puppet/CVE-2013-1655.yml, gems/puppet/CVE-2013-3567.yml, gems/puppet/CVE-2013-4761.yml, gems/ruby-openid/CVE-2013-1812.yml
5 new GHSA-based 2012/2013 advisories
yamllint and rake (green)
=> 5 new GHSA-based 2012/2013 advisories

gems/bootstrap/CVE-2018-14040.yml
One file (gems/bootstrap/CVE-2018-14040.yml) from GHSA lib/github_advisory_sync.rb run.
yamllint and "rake" both green.
=> 1 file from GHSA sync script run

gems/commonmarker/GHSA-48wp-p9qv-4j64.yml
Added GHSA advisory with multiple CVEs.
=> Added GHSA advisory with multiple CVEs

gems/actionpack/CVE-2011-1497.yml, gems/camaleon_cms/CVE-2023-30145.yml, gems/jquery-rails/CVE-2019-11358.yml
Ran GHSA sync script and got 2 modified advisories and 1 new advisories.
Ran yamllint and rake (both green).
=> Ran GHSA sync script and got 2 modified and 1 new

gems/RedCloth/CVE-2023-31606.yml, gems/avo/CVE-2023-34102.yml, gems/avo/CVE-2023-34103.yml
3 advisories from GHSA sync script
```
gems/avo/CVE-2023-34102.yml
gems/avo/CVE-2023-34103.yml
gems/RedCloth/CVE-2023-31606.yml
```
=> 3 advisories from GHSA sync script

gems/actionview/CVE-2023-23913.yml, gems/kredis/CVE-2023-27531.yml
Added 2 new rails-related (CVE-2023-23913 for actionview, CVE-2023-27531 for kredis) gems mentioned
on [discuss.rubyonrails.org ](https://discuss.rubyonrails.org).
=> Added 2 new rails-related gems

gems/rwiki/CVE-2006-2581.yml
Added 2006 rwiki advisory - CVE-2006-2581.yml.
Very early advisory.
Some advisories in Japanese.
=> Added 2006 rwiki advisory - CVE-2006-2581.yml

gems/bootstrap/CVE-2018-14042.yml
#400 mentions gems/bootstrap/CVE-2018-14042.yml so I deleted the file and recreated with sync script + editing.
=> Refreshed gems/bootstrap/CVE-2018-14042.yml

lib/github_advisory_sync.rb
Removed 2 blank lines before debug info so it is easier to remove debug info by script.
=> Removed 2 blank lines before debug info

gems/discordrb/CVE-2023-28102.yml
Added gems/discordrb/CVE-2023-28102.yml advisory.
=> Added gems/discordrb/CVE-2023-28102.yml advisory

gems/sup/CVE-2013-4478.yml, gems/sup/CVE-2013-4479.yml
Updated info in sup advisories in support for issue #164 .
=> Updated info in sup gem advisories in support for issue #164

gems/actionmailer/CVE-2013-4389.yml, gems/actionpack/CVE-2012-2660.yml, gems/actionpack/CVE-2012-2694.yml, gems/actionpack/CVE-2023-22792.yml, gems/actionpack/CVE-2023-22795.yml, gems/actionpack/CVE-2023-22797.yml, gems/activejob/CVE-2018-16476.yml, gems/activerecord/CVE-2012-2695.yml, gems/activerecord/CVE-2022-44566.yml, gems/activerecord/CVE-2023-22794.yml, gems/activesupport/CVE-2023-22796.yml, lib/github_advisory_sync.rb
Fixed framework field method to work - which fixed 11 existing advisories.
=> Fixed framework field method to work - which fixed 11 existing advisories

README.md, lib/github_advisory_sync.rb, spec/advisory_example.rb, spec/schemas/gem.yml, spec/schemas/ruby.yml
I know this is early, but wanted to at least have the field when we start getting the data.
=> Added cvss_v4 field

gems/rack/CVE-2022-44570.yml
GHSA sync script added cvss_v3 field to 1 advisory.
=> GHSA sync script added cvss_v3 field to 1 advisory

gems/actionpack/CVE-2023-28362.yml
GHSA sync script added ghsa: field to 1 advisory/file.
=> GHSA sync script added ghsa field to 1 advisory

gems/uri/CVE-2023-36617.yml
=> Add new uri gem advisory.

gems/spina/CVE-2023-3445.yml
GHSA sync created spina gem advisory.
=> GHSA sync created spina gem advisory

gems/bootstrap/CVE-2018-14042.yml
Added related:/cve: in support of issue #400.
=> Added related:/cve: in support of #400

gems/bootstrap/CVE-2018-14041.yml
Added CVE-2018-14041 advisory in support of #400.
=> Added CVE-2018-14041 advisory

gems/sprout/CVE-2013-6421.yml
Fixed indent for unattended_versions field.
=> Fixed indent for unattended_versions field

gems/activemodel/CVE-2016-0753.yml, gems/brakeman/CVE-2019-18409.yml, gems/rack/CVE-2018-16470.yml
Add double quotes around unaffected_versions values for 3 advisories.
=> Add double quotes around unaffected_versions values for 3 advisories

gems/hub/CVE-2014-0177.yml, gems/rails_admin/CVE-2016-10522.yml
GSHA sync: 1 new advisory +  modified (1 new line) advisory
=> GSHA sync: 1 new advisory +  modified (1 new line) advisory

gems/discordrb/CVE-2023-28102.yml
Updated gems/discordrb/CVE-2023-28102.yml wtih new data.
New gem release today so update is needed.
=> Updated gems/discordrb/CVE-2023-28102.yml wtih new data

gems/grpc/CVE-2023-32731.yml, gems/jquery-rails/CVE-2012-6708.yml, gems/jquery-rails/CVE-2015-9251.yml, gems/jquery-rails/CVE-2020-7656.yml, gems/nokogiri/CVE-2021-3518.yml, gems/nokogiri/CVE-2021-3537.yml, gems/sanitize/CVE-2023-36823.yml
Daily GHSA sync script run - redo/more manual checks
=> Daily (7/6) GHSA sync script run

gems/decidim-core/CVE-2023-32693.yml, gems/decidim-core/CVE-2023-34089.yml, gems/decidim-meetings/CVE-2023-34090.yml, gems/decidim/CVE-2023-32693.yml, gems/decidim/CVE-2023-34089.yml, gems/decidim/CVE-2023-34090.yml
GHSA Sync: 7/12-13/2023: 6 files
=> GHSA Sync: 7/12-13/2023: 6 files

gems/uri/CVE-2023-36617.yml
GHSA sync script added cvss_v3 field.
=> GHSA sync script added cvss_v3 field

gems/rswag/CVE-2023-38337.yml
GHSA sync added 1 new advisory.
=> GHSA sync added 1 new advisory

gems/rswag/CVE-2023-38337.yml
cvss_v3 field/value added to 1 advisory: gems/rswag/CVE-2023-38337.yml
=> cvss_v3 field/value added to 1 advisory

gems/openssl/CVE-2017-14033.yml, gems/webrick/CVE-2017-10784.yml
GHSA Sync: Added 2 advisories,
Had to change the release range on one of them to refer to the gem version, not the ruby language version.
=> GHSA Sync: Added 2 advisories

gems/logstash-core/CVE-2016-1000221.yml, gems/logstash-core/CVE-2016-10362.yml, gems/puppet/CVE-2016-2785.yml
GHSA Sync: Added/updated 3 new advisories.
=> GHSA Sync: Added/updated 3 new advisories

gems/protocol-http1/CVE-2023-38697.yml
GHSA Sync: 1 brand new protocol-http1 advisory
yamllint and rake (both green)
=> GHSA Sync: 1 brand new protocol-http1 advisory

gems/commonmarker/GHSA-7vh7-fw88-wj87.yml
GHSA Sync: 1 brand new advisory: gems/commonmarker/GHSA-7vh7-fw88-wj87.yml
=> GHSA Sync: 1 brand new advisory; afternoon

gems/puma/GHSA-68xg-gqqm-vgj8.yml
Add an entry for the new puma GHSA-68xg-gqqm-vgj8 vulnerability
=> Report puma GHSA-68xg-gqqm-vgj8 vulnerability

gems/puppet/CVE-2012-1053.yml, gems/puppet/CVE-2012-1906.yml
GHSA SYNC: 2 new puppet gem advisories
=> GHSA SYNC: 2 new puppet gem advisories

gems/mongrel/CVE-2007-6612.yml
GHSA SYNC: Added 1 brand new advisory: gems/mongrel/CVE-2007-6612.yml
=> GHSA SYNC: Added 1 brand new advisory

gems/jquery-ui-rails/CVE-2010-5312.yml, gems/jquery-ui-rails/CVE-2012-6662.yml
Two more brand new jquery-ui-rails advisories.
=> Two more brand new jquery-ui-rails advisories

gems/sidekiq/CVE-2023-26141.yml
Add patched version
https://github.com/sidekiq/sidekiq/blob/6-x/Changes.md
=> Add patched version: Sidekiq - CVE-2023-26141.yml

gems/decidim-templates/CVE-2023-36465.yml, gems/decidim/CVE-2023-36465.yml
GHSA Sync: Added 2 brand new advisories.
Only changes were line wrapping the "description:" field and added "notes" line.
=> GHSA Sync: Added 2 brand new advisories

gems/bolt/CVE-2023-5214.yml
GHSA Sync: Added 1 brand new advisory: gems/bolt/CVE-2023-5214.yml .
=> GHSA Sync: Added 1 brand new advisory: gems/bolt/CVE-2023-5214.yml 

gems/svg_optimizer/CVE-2023-46035.yml
GHSA Sync: Added ghsa field to 1 advisory: gems/svg_optimizer/CVE-2023-46035.yml
=> GHSA Sync: Added ghsa field to 1 advisory

gems/RedCloth/CVE-2023-31606.yml
1. Updated CVE-2023-31606.yml with a RedCloth patched version
2. Added reference to the PR and the line of code changed
=> Add a patched version for CVE-2023-31606

gems/bootstrap-wysihtml5-rails/CVE-2019-19919.yml
Fix #718
Please let me know if you need anything else. Thanks!
=> CVE 2019-19919 for bootstrap-wysihtml5-rails

gems/bootstrap-wysihtml5-rails/CVE-2019-19919.yml
Added cvss_v3 field to 1 advisory: gems/bootstrap-wysihtml5-rails/CVE-2019-19919.yml
=> GHSA Sync: Added cvss_v3 field to 1 advisory

gems/devise/CVE-2015-8314.yml, gems/flash_tool/CVE-2013-2513.yml, gems/jruby-openssl/CVE-2009-4123.yml, gems/xaviershay-dm-rails/CVE-2015-2179.yml
GHSA Sync: Added 'cvss_v3' field to 4 advisories
=> GHSA Sync: Added 'cvss_v3' field to 4 advisories

gems/resque-scheduler/CVE-2022-44303.yml, gems/resque/CVE-2023-50724.yml, gems/resque/CVE-2023-50725.yml, gems/resque/CVE-2023-50727.yml
GHSA Sync: 4 brand new advisories:
```
gems/resque/CVE-2023-50724.yml
gems/resque/CVE-2023-50725.yml
gems/resque/CVE-2023-50727.yml
gems/resque-scheduler/CVE-2022-44303.yml
```
=> GHSA Sync: 4 brand new advisories

gems/activeadmin/CVE-2023-51763.yml
GHSA Sync: 1 brand new advisory: gems/activeadmin/CVE-2023-51763.yml
**Note: Had to update 1 gem: kwalify before "rake" was green.**
=> GHSA Sync: 1 brand new advisory

gems/devise-two-factor/CVE-2024-0227.yml, gems/puppet/CVE-2012-1987.yml, gems/puppet/CVE-2012-1988.yml
GHSA Sync: 3 brand new advisories:
* gems/devise-two-factor/CVE-2024-0227.yml
* gems/puppet/CVE-2012-1987.yml
* gems/puppet/CVE-2012-1988.yml
=> GHSA Sync: 3 brand new advisories

gems/avo/CVE-2024-22191.yml, gems/puppet/CVE-2011-0528.yml, gems/puppet/CVE-2011-3869.yml, gems/puppet/CVE-2011-3870.yml, gems/puppet/CVE-2011-3871.yml
GHSA Sync: 5 brand new advisories:
```
gems/avo/CVE-2024-22191.yml
gems/puppet/CVE-2011-0528.yml
gems/puppet/CVE-2011-3869.yml
gems/puppet/CVE-2011-3870.yml
gems/puppet/CVE-2011-3871.yml
```
=> GHSA Sync: 5 brand new advisories

gems/rails/CVE-2009-2422.yml
GHSA SYNC: 1 modified advisory: gems/rails/CVE-2009-2422.yml
=> GHSA SYNC: 1 modified advisory

gems/sidekiq-unique-jobs/CVE-2024-25122.yml
GHSA SYNC: 1 brand new advisory (with embedded formatting): gems/sidekiq-unique-jobs/CVE-2024-25122.yml
=> GHSA SYNC: 1 brand new advisory (with embedded formatting)

gems/rack/CVE-2024-25126.yml, gems/rack/CVE-2024-26141.yml, gems/rack/CVE-2024-26146.yml
GHSA Sync: Added ghsa: field to 3 advisories.
=> GHSA Sync: Added ghsa: field to 3 advisories

gems/actionpack/CVE-2024-26142.yml, gems/actionpack/CVE-2024-26143.yml, gems/activestorage/CVE-2024-26144.yml, gems/json-jwt/CVE-2023-51774.yml
GHSA SYNC: 1 brand new and 3 modified (added ghsa:, cvss_v3 fields) advisories.
=> GHSA SYNC: 1 brand new and 3 modified (added ghsa:, cvss_v3 fields) advisories

gems/json-jwt/CVE-2023-51774.yml
See https://github.com/nov/json-jwt/issues/121 and https://github.com/nov/json-jwt/commits/v1.15.3/ for the code
=> Update CVE-2023-51774 with patch version for 1.15.3

gems/phlex/CVE-2024-28199.yml
GHSA SYNC: 1 brand new advisory: gems/phlex/CVE-2024-28199.yml
=> GHSA SYNC: 1 brand new advisory: gems/phlex/CVE-2024-28199.yml

gems/discordrb/CVE-2023-28102.yml
GHSA SYNC: Modified 1 advisory - Added ghsa field and one url: value.
=> GHSA SYNC: Modified 1 advisory

gems/rdoc/CVE-2024-27281.yml, gems/stringio/CVE-2024-27280.yml
GHSA SYNC: Added ghsa: fields to 2 advisories:
* gems/rdoc/CVE-2024-27281.yml
* gems/stringio/CVE-2024-27280.yml
=> GHSA SYNC: Added ghsa: fields to 2 advisories

gems/carrierwave/CVE-2024-29034.yml
GHSA SYNC: 1 new advisory: gems/carrierwave/CVE-2024-29034.yml
=> GHSA SYNC: 1 new advisory

gems/rack/CVE-2024-25126.yml
GHSA SYNC: Added cvss_v3 field to gems/rack/CVE-2024-25126.yml file.
=> GHSA SYNC: Added cvss_v3 field

gems/actiontext/CVE-2024-34341.yml
Fix #783.
I hope this works for you; if not, I'm happy to apply changes.
=> add CVE-2024-34341 for ActionText

gems/actionpack/CVE-2024-28103.yml, gems/actiontext/CVE-2024-32464.yml
GHSA SYNC: 2 brand new advisories:
* gems/actionpack/CVE-2024-28103.yml
* gems/actiontext/CVE-2024-32464.yml
=> GHSA SYNC: 2 brand new advisories

gems/avo/CVE-2023-34102.yml, gems/decidim/CVE-2023-47634.yml, spec/advisory_example.rb
Added rspec check for double embedded newlines + fixed 2 existing advisories.
=> Added rspec check for double embedded newlines + fixed 2 exisiting advisories

gems/stringio/CVE-2024-27280.yml
Added cvss_v3 field to advisory: gems/stringio/CVE-2024-27280.yml
=> Added cvss_v3 field to advisory

gems/rails_admin/CVE-2024-39308.yml, gems/stringio/CVE-2024-27280.yml
GHSA SYNC: Added brand new advisory: gems/rails_admin/CVE-2024-39308.yml
=> GHSA SYNC: Added brand new advisory

gems/rexml/CVE-2024-39908.yml
Found new CVE on Ruby web site. No GHSA or CVSS values yet.
=> Found new CVE on Ruby web site

gems/rexml/CVE-2024-41123.yml, gems/rexml/CVE-2024-41946.yml
Two brand new rexml advisories:
* gems/rexml/CVE-2024-41123.yml
* gems/rexml/CVE-2024-41946.yml
=> Two brand new rexml advisories

gems/bootstrap-sass/CVE-2018-14040.yml, gems/rexml/CVE-2024-41946.yml
GHSA SYNC: 1 modified (added ghsa: and cvss_v3 fields) advisory; 1 brand new advisory:
* gems/rexml/CVE-2024-41946.yml
* gems/bootstrap-sass/CVE-2018-14040.yml
=> GHSA SYNC: 1 modified advisory; 1 brand new advisory

gems/request_store/CVE-2024-43791.yml
GSHA SYNC: 1 brand new advisory: gems/request_store/CVE-2024-43791.yml
=> GSHA SYNC: 1 brand new advisory

gems/openc3/CVE-2024-43795.yml, gems/openc3/CVE-2024-46977.yml
GHSA SYNC: Add cvss_v3 field to 2 advisories:
* gems/openc3/CVE-2024-43795.yml
* gems/openc3/CVE-2024-46977.yml
=> GHSA SYNC: Add cvss_v3 field to 2 advisories

gems/actiontext/CVE-2024-47888.yml
Added a reference to 1 advisory: gems/actiontext/CVE-2024-47888.yml
=> Added a reference to 1 advisory

gems/cgi/CVE-2025-27219.yml, gems/cgi/CVE-2025-27220.yml, gems/oxidized-web/CVE-2025-27590.yml, gems/uri/CVE-2025-27221.yml
GHSA SYNC: 3 modified and 1 brand new advisory
* modified:   gems/cgi/CVE-2025-27219.yml
* modified:   gems/cgi/CVE-2025-27220.yml
* new file:   gems/oxidized-web/CVE-2025-27590.yml
* modified:   gems/uri/CVE-2025-27221.yml
=> GHSA SYNC: 3 modified and 1 brand new advisory

gems/resolv/CVE-2025-24294.yml
Existing advisory: Added more references + update CVSS score based on new reference
=> Added more references + update CVSS score based on new reference

README.md
Added "e.g" (example) text to README for framework: field
=> Added "e.g" (example) text to README for framework: field
