gems/spree/OSVDB-119205.yml

Please double check, especially the versions ;-)
Issue Ref.: https://github.com/rubysec/ruby-advisory-db/issues/132
http://osvdb.org/show/osvdb/119205
https://spreecommerce.com/blog/security-updates-2015-3-3
https://rubygems.org/gems/spree/versions

Add Spree Ruby gem advisory

---

gems/activesupport/CVE-2015-3226.yml

According to https://groups.google.com/forum/#!searchin/rubyonrails-core/CVE-2015-3226/rubyonrails-core/qBUqVlXERag/kuH3wQk1kxUJ, all versions until rails 4.1 are not affected.

Until 4.1, rails is not affected by CVE-2015-3226

---

gems/redcarpet/CVE-2015-5147.yml

OSVDB has assigned OSVDB-123859 to this (though it doesn't show up on their website due to technical problems).
Also add CVSSv2 base score from NVD.

Add reference to OSVDB-123859 to redcarpet's CVE-2015-5147

---

gems/i18n/OSVDB-121500.yml

**NOT READY FOR MERGING**
http://osvdb.org/show/osvdb/121500
This refers to https://github.com/svenfuchs/i18n/pull/289, which hasn't yet made it to a released version of `i18n`. Perhaps somebody could poke them to get that done so we can add the advisory to the db.

Adding OSVDB-121500 for i18n

---

gems/nokogiri/OSVDB-101179.yml
gems/nokogiri/OSVDB-118481.yml

OSVDB-118481 was ridiculously difficult to track down. Had to search through nokogiri commits and changelogs to figure out what it was referring to. Doesn't seem like a CVE was requested either.

Add OSVDB-118481 and make some changes to OSVDB-101179 for nokogiri

---

gems/passenger/CVE-2014-1831.yml
gems/passenger/CVE-2014-1832.yml

OSVDB-102613 is really two separate CVEs for similar (but slightly different) issues, so split it so we have a record of both CVEs.

Separate OSVDB-102613 into CVE-2014-1831 and CVE-2014-1832

---

scripts/post-advisories.sh

Forgot to include `rake` in the command.

Add missing argument to `bundle` to execute advisories rake task

---

gems/sup/CVE-2013-4478.yml
gems/sup/CVE-2013-4479.yml

Think this just makes more sense, and it has way more information than the OSVDB entry.

Use actual advisory URL for sup vulnerabilties

---

gems/awesome_spawn/CVE-2014-0156.yml

This is a PR to include CVE-2014-0156 OS command injection vulnerability in awesome_spawn.
The vulnerability was found by Jan Rusnacko, reported directly to upstream maintainer on 2014-03-28, CVE ID was assigned by Red Hat and the issue was fixed in commit https://github.com/ManageIQ/awesome_spawn/commit/e524f85f1c6e292ef7d117d7818521307ac269ff

Adding CVE-2014-0156

---

gems/bcrypt/OSVDB-62067.yml
gems/dragonfly/OSVDB-96798.yml
gems/fog-dragonfly/OSVDB-110439.yml
gems/fog-dragonfly/OSVDB-90647.yml
gems/fog-dragonfly/OSVDB-97854.yml

As per #170, add directories for both old and new versions of a gem name. For the old version, I leave `patched_versions` blank where appropriate.

Handle two renamed gems

---

gems/spree/OSVDB-119205.yml
gems/spree/OSVDB-125699.yml
gems/spree/OSVDB-125701.yml
gems/spree/OSVDB-125712.yml
gems/spree/OSVDB-125713.yml
gems/spree/OSVDB-69098.yml
gems/spree/OSVDB-73751.yml
gems/spree/OSVDB-76011.yml
gems/spree/OSVDB-81505.yml
gems/spree/OSVDB-81506.yml
gems/spree/OSVDB-90865.yml
gems/spree/OSVDB-91216.yml
gems/spree/OSVDB-91217.yml
gems/spree/OSVDB-91218.yml
gems/spree/OSVDB-91219.yml
gems/spree_auth/OSVDB-90865.yml
gems/spree_auth_devise/OSVDB-90865.yml

Add a bunch of advisories for `spree`, as well as modify two existing ones.
Note that `spree` is a bit weird in that it's really split into a bunch of different gems. These gems all keep the same version for the release. Some of this fixes cross these sub-gem boundaries, so hard to keep track of things. I made the decision to just keep everything tied to the `spree` gem itself, even though some other sub-gems are affected.

Add / modify advisories for spree

---

rubies/ruby/OSVDB-90587.yml

The current advisory uses `~>` to explicitly flag only two versions as patched. This causes automated tools to flag Ruby 2.1.0+ as vulnerable.
[The advisory](http://www.osvdb.org/show/osvdb/90587) states "Upgrade to version 1.9.3-p392, or higher, to address this vulnerability." Ruby 2.0.0.0 was released after 1.9.3-p392, so a simple `>=` is adequate to cover all newer versions.

Fixing OSVDB-90587's patched versions

---

Gemfile
lib/cf_scrape.py
lib/osvdb_scrape.rb

Add a Python script `lib/cf_scrape.py` that uses `cfscrape` (https://github.com/Anorov/cloudflare-scrape) in order to scrape OSVDB's advisory pages.
Rename `lib/scrape.rb` to `lib/osvdb_scrape.rb` and update it to work with separate Python script, as well as support just passing the ID directly.
Fixes #174.

Fix OSVDB scraper to work with CloudFlare's protection

---

gems/nokogiri/CVE-2015-1819.yml

Adds advisories for vulnerabilities in libxml2 and libxslt libraries that have recently been patched in Nokogiri.
Mentioned in release notes for Nokogiri v1.6.7.rc4: https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.rdoc#167rc4--2015-11-22

Add advisories for libxml2 and libxslt vulnerabilties patched in Nokogiri

---

gems/nokogiri/CVE-2015-5312.yml

Nokogiri gem version 1.6.7.1 updates the vendored libxml2 to version 1.9.3 - fixing multiple vulnerabilities.
I've included the link to the ruby-sec-ann announcement, and followed the same format as a prior Nokogiri release with multiple vulnerabilities, by having one entry, and using the `related` field for the other CVE's.

multiple nokogiri vulnerabilities via libxml2

---

rubies/ruby/CVE-2015-7551.yml

Per https://www.ruby-lang.org/en/news/2015/12/16/unsafe-tainted-string-usage-in-fiddle-and-dl-cve-2015-7551/, Ruby 2.3.0 preview 1 and preview 2 are vulnerable, but 2.3.0 is not (revisions prior to trunk revision 53153 are vulnerable. 2.3.0 is revision 53290). Adding a patched_version line for 2.3.0+. This is consistent with existing advisories (patch versions are represented using "x.y.z.patch.1", and 2.3.0 is >= 2.3.0.patch.2).

Fixing CVE-2015-7551's patched versions

---

README.md

The current link is dead, the proposed one might not have exactly the same content, but it seems at least related.

Update CVSSv2 link in README

---

rubies/ruby/CVE-2015-1855.yml

CVE-2015-1855 was patched for Ruby 2.2.2 and all future versions of Ruby. That means in addition to `~> 2.2.2` being patched, `>= 2.3.0` is patched as well.

Ruby >= 2.3.0 has been patched for CVE-2015-1855

---

gems/rack-mini-profiler/CVE-2016-4442.yml

Although this was published on http://seclists.org/oss-sec/2016/q2/516, there is no description available (yet) at https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-4442.

Add CVE-2016-4442 for rack-mini-profiler

---

gems/doorkeeper/CVE-2016-6582.yml

URL is a placeholder to the GitHub commit diff of the fix until mailing lists moderate the public disclosure.

Add CVE-2016-6582 for doorkeeper

---

gems/colorscore/CVE-2015-7541.yml

Patched in https://github.com/quadule/colorscore/commit/570b5e854cecddd44d2047c44126aed951b61718

Patched version of colorscore for CVE-2015-7541

---

gems/actionpack/CVE-2016-0752.yml
gems/actionpack/CVE-2016-2097.yml
gems/actionpack/CVE-2016-6316.yml

Since actionview was not a separate gem prior to Rails 4.1, the following CVEs were not being reported by bundler-audit for Rails 3.2 or Rails 4.0:
- CVE-2016-0752
- CVE-2016-2097
- CVE-2016-6316
This resolves the issue by creating copies of those CVEs, but for the actionpack gem, where the actionview code lived in Rails 4.1 and prior.
I'm not exactly sure this duplicate file approach is the best solution, so let me know if you have any other suggestions for how to manage this. But after the Rails security updates yesterday, I was surprised when bundler-audit still didn't report any new issues for some Rails 3.2 apps, so I wanted to try to fix this in some fashion.

Fix missing actionview vulnerabilities for Rails 3.2 and Rails 4.0

---

gems/archive-tar-minitar/CVE-2016-10173.yml
gems/minitar/CVE-2016-10173.yml

This sets the correct patched version for `archive-tar-minitar` to `0.6.1` (instead of `0.60`). I took the liberty to set the patched version to `0.6.1`, and not `0.6.0`, because the latter had some issues (https://github.com/halostatue/minitar/issues/23 and https://github.com/halostatue/minitar/issues/24), which triggered a new release shortly thereafter. I'm not sure why the seemingly broken `0.6.0` hasn't been pulled from RubyGems.

Set correct patched versions for (archive tar) minitar gems

---

gems/actionview/CVE-2016-6316.yml
gems/activerecord/CVE-2016-6317.yml

`bundle-audit` was failing like so, because it didn't consider 4.2.8 as having patches for these 2 vulnerabilities:
```sh
Updating ruby-advisory-db ...
Cloning into '/root/.local/share/ruby-advisory-db'...
Updated ruby-advisory-db
ruby-advisory-db: 282 advisories
Name: actionview
Version: 4.2.8
Advisory: CVE-2016-6316
Criticality: Unknown
URL: https://groups.google.com/forum/#!topic/rubyonrails-security/I-VWr034ouk
Title: Possible XSS Vulnerability in Action View
Solution: upgrade to ~> 4.2.7.1, >= 5.0.0.1
Name: activerecord
Version: 4.2.8
Advisory: CVE-2016-6317
Criticality: Unknown
URL: https://groups.google.com/forum/#!topic/rubyonrails-security/rgO20zYW33s
Title: Unsafe Query Generation Risk in Active Record
Solution: upgrade to ~> 4.2.7.1
Vulnerabilities found!
```
Based on …

ActionView and ActiveRecord 4.2.8 are patched for these vulnerabilities

---

gems/actionpack/CVE-2015-7576.yml
gems/actionpack/CVE-2016-0751.yml
gems/actionpack/CVE-2016-0752.yml
gems/actionview/CVE-2016-0752.yml
gems/activemodel/CVE-2016-0753.yml
gems/activerecord/CVE-2015-7577.yml

Rails `5.1.0.alpha` was released yesterday and `bundler:audit` reports some issues that were already fixed in `5.0.0.beta1.1`.
Since `5.1.0.alpha` bases on `5.0.0.rc1` (see: https://github.com/rails/rails/commit/8ecc5ab1d88532a239f17c7520ed922c7579b01c) I am pretty sure that we can change the entries in the list of `patched_versions` from `~> 5.0.0.beta1.1` to `>= 5.0.0.beta1.1` to include Rails `5.1.0`.
I suggest [files?w=1](284/files?w=1) to review changed files.

Rails `5.1.0.alpha` bases on `5.0.0.rc1`

---

gems/rubyzip/CVE-2017-5946.yml

This PR adds rubyzip directory traversal vulnerability to advisories list.
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-5946
@reedloden @mveytsman

add rubyzip directory traversal advisory

---

CONTRIBUTING.md
README.md
spec/advisory_example.rb

This removes a deprecation warning introduced by Ruby 2.4.0 that appears when running specs.
This fix works, because `Integer` exists in older versions of Ruby too and is a superclass of `Fixnum`.

Remove `warning: constant ::Fixnum is deprecated`

---

gems/nokogiri/CVE-2016-4658.yml

This adds nokogiri CVE-2016-4658 and CVE-2016-5131.
https://groups.google.com/forum/#!topic/ruby-security-ann/R0dyurqxk8o

Add nokogiri CVE-2016-4658 and CVE-2016-5131

---

gems/mail/OSVDB-131677.yml

See 
https://github.com/mikel/mail/pull/1097
and 
https://hackerone.com/reports/137631
The vulnerability seems to have actually been addressed by versions 2.5.5 and 2.6.6. Please verify that my `patched_versions` specifiers reflect this correctly.

Update patched versions for mail gem vulnerability OSVDB-131677

---

gems/mail/OSVDB-131677.yml
rubies/ruby/CVE-2015-9096.yml

Add CVE-2015-9096 for Ruby Net::SMTP command injection.
Migrate Mail OSVDB-131677 to CVE-2015-9097.
/cc @unak @shugo @reedloden @phillmv

CVE-2015-9096 for Ruby SMTP injection. Migrate Mail OSVDB-131677 to CVE-2015-9097.

---

gems/recurly/CVE-2017-0905.yml

SSRF vulnerability in Resource#find method of the `recurly` gem.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-0905

Recurly CVE-2017-0905

---

gems/yajl-ruby/CVE-2017-16516.yml

This adds a recent high-severity CVE for `yajl-ruby`.

yajl-ruby CVE-2017-16516

---

gems/redis-store/CVE-2017-1000248.yml

Covers [CVE-2017-1000248](https://nvd.nist.gov/vuln/detail/CVE-2017-1000248)

Add redis-store 1.3.0 unsafe load vulnerability

---

libraries/rubygems/CVE-2017-0899.yml
libraries/rubygems/CVE-2017-0900.yml
libraries/rubygems/CVE-2017-0901.yml
libraries/rubygems/CVE-2017-0902.yml

note: They are only ruby builtin RubyGems version.
c.f. https://bugs.ruby-lang.org/issues/13842

Add RubyGems fixed versions.

---

gems/recurly/CVE-2017-0905.yml

Current and future releases are fixed. https://github.com/recurly/recurly-client-ruby/commit/1bb0284d6e668b8b3d31167790ed6db1f6ccc4be

Add current version for recurly

---

gems/rubocop/CVE-2017-8418.yml

RuboCop 0.48.1 and earlier does not use /tmp in safe way,
allowing local users to exploit this to tamper with cache
files belonging to other users.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-8418
https://github.com/bbatsov/rubocop/issues/4336

Add Rubocop CVE-2017-8418

---

rubies/ruby/CVE-2015-9096.yml

CVE-2015-9096 was fixed with Ruby 2.3.5, too. But Ruby 2.2 series was not fixed.
* Ruby 2.3: fixed https://github.com/ruby/ruby/pull/1647
* Ruby 2.2: not fixed https://github.com/ruby/ruby/pull/1648

Add CVE-2015-9096 fixed versions.

---

gems/paperclip/CVE-2017-0889.yml

GitHub reported a security vulnerability in the `paperclip` ruby gem of one project I've been currently involved in. `bundler-audit` is not detecting such vulnerability. This PR aims to add a new entry for the paperclip gem into `ruby-advisory-db`.
I'd also like to mention @rongutierrez for releasing a useful [blog post](https://medium.com/in-the-weeds/all-about-paperclips-cve-2017-0889-server-side-request-forgery-ssrf-vulnerability-8cb2b1c96fe8) providing details on the vulnerability as well as recommended actions.

Add CVE-2017-0889

---

gems/nokogiri/CVE-2017-15412.yml

> CVE-2017-15412 was addressed in libxml v2.9.6, which Nokogiri's latest release (v1.8.1) has not yet vendored. Upgrading Nokogiri to distribute libxml v2.9.6 or later is necessary to address this vulnerability.
https://github.com/sparklemotion/nokogiri/issues/1714

Add CVE-2017-15412 for nokogiri

---

gems/nokogiri/CVE-2017-16932.yml

> CVE-2017-16932 was addressed in libxml 2.9.5, and so Nokogiri v1.8.1 (released 2017-09-19) has already addressed this vulnerability.
https://github.com/sparklemotion/nokogiri/issues/1714

Add CVE-2017-16932 for nokogiri

---

gems/doorkeeper/CVE-2018-1000088.yml

Per https://github.com/doorkeeper-gem/doorkeeper/pull/970#issuecomment-367213342

Add CVE-2018-1000088

---

gems/sinatra/CVE-2018-7212.yml

This is a Sinatra bug that affects Windows machines prior to v2.0.1.

Add CVE-2018-7212

---

gems/rack-protection/CVE-2018-7212.yml

CVE-2018-7212 is in rack-protection which is in the same Github repo as Sinatra as of version 2.0.0. The fix was also backported to rack-protection 1.5.4 in this branch:
https://github.com/sinatra/rack-protection/commits/stable-1.5
Fixes #330

Fix CVE-2018-7212 to refer to rack-protection with correct fix versions

---

rubies/ruby/CVE-2017-17742.yml

This adds https://www.ruby-lang.org/en/news/2018/03/28/http-response-splitting-in-webrick-cve-2017-17742/
It seems like the CVE details are not publicly available yet - I followed the link in the ruby-lang.org link above to http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-17742 but there are no details there so I don't know what the CVSS scores are.

Add MRI Ruby CVE: 2017-17742

---

rubies/ruby/CVE-2018-6914.yml
rubies/ruby/CVE-2018-8777.yml
rubies/ruby/CVE-2018-8778.yml
rubies/ruby/CVE-2018-8779.yml
rubies/ruby/CVE-2018-8780.yml

This adds the five remaining CVEs mentioned in https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/

Add missing ruby CVEs which prompted ruby release on 2018-03-28

---

gems/sinatra/CVE-2018-11627.yml

This CVE was flagged by GitHub but missed by bundle-audit as sinatra not in the advisory DB.

Add CVE-2018-11627 for Sinatra (#337)

---

gems/sinatra/CVE-2018-11627.yml

- `2.0.0.beta[1-2]` and `2.0.0.rc[1-6]` are also affected, but accidentally included to unaffected versions as they are `< 2.0.0`.
- In the commit history, `2.0.0-alpha` exists before `2.0.0.beta1` and it's not affected.  Since rubygems treats `2.0.0-alpha` as between `2.0.0.beta2` and `2.0.0.rc1`, we need to explicitly add it to unaffected versions.

Remove pre-releases from unaffected versions

---

gems/doorkeeper/CVE-2018-1000211.yml

~~Merge pending the release of 5.0.0.rc2 and 4.4.0: https://github.com/doorkeeper-gem/doorkeeper/pull/1120#issuecomment-405283007~~ they are now released

Add CVE-2018-1000211 for Doorkeeper

---

gems/archive-tar-minitar/CVE-2016-10173.yml
gems/minitar/CVE-2016-10173.yml

This is a small fix to `minitar` and `archive-mini-tar` for CVE-2016-10173.
The true fix version for both is `0.6.0` as can be seen in this commit: https://github.com/halostatue/minitar/commit/e25205ecbb6277ae8a3df1e6a306d7ed4458b6e4

fixed minitar patched versions

---

gems/grape/CVE-2018-3769.yml

This fixed the advisory for CVE-2018-3769 which has two inaccuracies in it:
- the gem name is `grape` not `ruby-grape`
- the fix version is `1.1.0` as can be be confirmed here: https://github.com/ruby-grape/grape/pull/1763#issuecomment-410463219

fixed the grape advisory

---

gems/rubyzip/CVE-2018-1000544.yml

The rubyzip community is working on CVE-2018-1000544 in the following PR: https://github.com/rubyzip/rubyzip/pull/376
Earlier they worked on a possible fix but then introduced the previously mentioned PR, which disables symlink support. 
The gem version got increased from 1.2.1 to 1.2.2. in the PR and some people are already using the branch of the PR. Currently their Travis CI build passes but the coverage check does not, although only the version has been updated in the latest commit.
So far, no objection has been raised regarding the PR and it seems that version 1.2.2 will be the next release, closing the vulnerability.
I have therefore adapted the upcoming version of the rubyzip gem as patched version in the corresponding file for CVE-2018-1000544.
It is clear to me that this PR …

Add patched version for CVE-2018-1000544

---

gems/rubyzip/CVE-2018-1000544.yml

The supplied `patched_version` is incorrect. See rubyzip/rubyzip#315 for more details.

Fix gem versions in rubyzip advisory

---

rubies/ruby/CVE-2018-16395.yml

This PR adds CVE 2018-16395 impacting Ruby.
Note that no new preview release of Ruby 2.6.0 has been announced so don't believe there is a patched version that can be indicated at this time.

Add Ruby CVE 2018-16395 (#358)

---

gems/railties/CVE-2019-5420.yml

This adds `unaffected_versions` to prevent CVE-2019-5420 being triggered as a warning for `railties` affected versions `< 5.2.0`.
I upgraded to `5.0.7.2` and seeing this error, which is incorrect according to the CVE:
```
Name: railties
Version: 5.0.7.2
Advisory: CVE-2019-5420
Criticality: Unknown
URL: https://groups.google.com/forum/#!topic/rubyonrails-security/IsQKvDqZdKw
Title: Possible Remote Code Execution Exploit in Rails Development Mode
Solution: upgrade to >= 5.2.2.1, ~> 5.2.2, >= 6.0.0.beta3
```
Fixes https://github.com/rubysec/ruby-advisory-db/issues/381

Add unaffected versions for railties versions <5.2.0 for CVE-2019-5420

---

libraries/rubygems/CVE-2019-8320.yml
libraries/rubygems/CVE-2019-8321.yml
libraries/rubygems/CVE-2019-8322.yml
libraries/rubygems/CVE-2019-8323.yml
libraries/rubygems/CVE-2019-8324.yml
libraries/rubygems/CVE-2019-8325.yml

Disclosed at https://blog.rubygems.org/2019/03/05/security-advisories-2019-03.html
It seems even though they have CVEs at the post, they are not yet in the mitre db.

Add new CVEs from rubygems

---

gems/railties/CVE-2019-5420.yml

https://github.com/rubysec/ruby-advisory-db/pull/382 set the `unaffected_versions` for this CVE to `["< 5.2.0"]`. This PR just updates the `description` to match that.

update desc of CVE-2019-5420 to indiciate unaffected versions

---

gems/devise/CVE-2019-5421.yml

Still need CVE ID for this, as well as final description updates...

Add CVE-2019-5421 for devise

---

gems/bootstrap-sass/CVE-2019-10842.yml

* Closes issue #385.
* CVE number taken from https://github.com/twbs/bootstrap-sass/issues/1195#issuecomment-479616107
* More context on the issue: https://snyk.io/blog/malicious-remote-code-execution-backdoor-discovered-in-the-popular-bootstrap-sass-ruby-gem/

Add CVE-2019-10842 - remote code execution in bootstrap-sass

---

gems/chartkick/CVE-2019-12732.yml

For https://github.com/ankane/chartkick/issues/488

Added CVE-2019-12732 for Chartkick

---

Gemfile
Gemfile.lock
README.md
Rakefile
lib/github_advisory_sync.rb

This is a script which imports data from the [GitHub Security Advisory API](https://developer.github.com/v4/object/securityadvisory/) into this advisory database.
- Person runs the script using: `bundle exec rake sync_github_advisories`
- Script writes yaml advisory files for all rubygem advisories that GitHub has, which RubySec does not already have
- Person reviews each file carefully, makes sure data looks right
- Person has to set the `patched_versions` and `unaffected_versions` versions manually, using comments in the file.  GitHub data is structured opposite of RubySec unfortunately: GitHub identifies version range which are vulnerable, RubySec identifies version ranges which are not vulnerable.  The translation from the GitHub way to the RubySec way is manual (but assisted by …

MVP script to sync github advisory data in

---

README.md
gems/yard/GHSA-xfhh-rx56-rxcr.yml
spec/advisory_example.rb

This PR is the first add of a GitHub Security Advisory to this dataset.
The advisory is this one, on `yard`, which has been fixed in latest `0.9.20` version: https://github.com/lsegal/yard/security/advisories/GHSA-xfhh-rx56-rxcr
Since this advisory does not have a CVE, only a "GHSA ID", some small changes to the validation tests were needed in order to allow advisory records to have a ghsa field but no cve/osvdb.  Also, a small tweak to the README is included so ghsa is now a field in the advisory "schema".
This PR was partially made by the GitHub sync script, which itself required some changes to work with non-CVE advisories, and those are in a separate PR: https://github.com/rubysec/ruby-advisory-db/pull/396

Add first GitHub Security Advisory on yard: GHSA-xfhh-rx56-rxcr

---

gems/jekyll/CVE-2018-17567.yml

This adds an important CVE on jekyll:
- https://nvd.nist.gov/vuln/detail/CVE-2018-17567
- https://jekyllrb.com/news/2018/09/19/security-fixes-for-3-6-3-7-3-8/
- https://github.com/jekyll/jekyll/pull/7224
This advisory was made using the GitHub Advisory sync sync script for ruby-advisory-db.  This script is currently in a [draft PR](https://github.com/rubysec/ruby-advisory-db/pull/392).  This is an initial test of the sync script.

add CVE-2018-17567 on jekyll

---

gems/doorkeeper-openid_connect/CVE-2019-9837.yml

This adds https://nvd.nist.gov/vuln/detail/CVE-2019-9837 into the DB.
Some additional relevant references for this vulnerability:
- https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/master/CHANGELOG.md#v154-2019-02-15
- https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/61
- https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/66
This advisory was made using the GitHub Advisory sync sync script for ruby-advisory-db.  This script is currently in a [draft PR](https://github.com/rubysec/ruby-advisory-db/pull/392).  This is an initial test of the sync script.

Add CVE-2019-9837 for doorkeeper-openid_connect

---

gems/omniauth/CVE-2015-9284.yml

For a CSRF vulnerability in OmniAuth: https://github.com/omniauth/omniauth/pull/809
There's currently no patched version of OmniAuth to address this vulnerability, but there is an additional [omniauth-rails_csrf_protection gem](https://github.com/cookpad/omniauth-rails_csrf_protection) that patches the vulnerability if OmniAuth is being used with Rails. So I added a related link to this gem, but I'm open to suggestions for other ways to clarify this. See https://github.com/omniauth/omniauth/pull/809#issuecomment-497376674 and https://github.com/omniauth/omniauth/pull/809#issuecomment-497462504 for context on this separate gem and why it's only applicable to Rails usage.

Add CVE-2015-9284 for OmniAuth

---

gems/mini_magick/CVE-2019-13574.yml

This adds an important CVE on mini_magick
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-13574
- https://github.com/minimagick/minimagick/releases/tag/v4.9.4

Add CVE-2019-13574 on mini_magick

---

gems/rest-client/CVE-2019-15224.yml

I added rest-client/CVE-2019-15224.yml. Only 1.6.13 was written in https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-15224.
but yanked version in 
https://rubygems.org/gems/rest-client/versions is below.
> 1.6.13 - August 14, 2019 (114KB) yanked
> 1.6.12 - August 14, 2019 (113KB) yanked
> 1.6.11 - August 14, 2019 (113KB) yanked
> 1.6.10 - August 13, 2019 (11.5KB) yanked
So I was set unaffected version to ...1.6.9 and 1.7.0.rc1... .
If 1.6.10 - 1.6.12 was not affected, I will change unaffected version.
see. https://github.com/rest-client/rest-client/issues/713

Add CVE-2019-15224 for rest-client.

---

gems/nokogiri/CVE-2019-5477.yml
gems/rexical/CVE-2019-5477.yml

Source: https://nvd.nist.gov/vuln/detail/CVE-2019-5477

Update CVSS score for CVE-2019-5477  nokogiri

---

gems/airbrake-ruby/CVE-2019-16060.yml

For https://github.com/airbrake/airbrake-ruby/issues/468.
There's also an issue in https://github.com/rubysec/bundler-audit/issues/221 that is directly related to this PR.
Sorry, I'm not sure how to obtain a CVE. Any assistance is appreciated.

Add CVE-2019-16060 for airbrake-ruby

---

rubies/ruby/CVE-2019-15845.yml
rubies/ruby/CVE-2019-16201.yml
rubies/ruby/CVE-2019-16254.yml
rubies/ruby/CVE-2019-16255.yml

From
* https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/
* https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-5-7-released/
* https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-4-8-released/
* https://www.ruby-lang.org/en/news/2019/10/02/ruby-2-4-9-released/

Add CVE-2019-15845, CVE-2019-16201, CVE-2019-16254, CVE-2019-16255

---

Gemfile
Gemfile.lock
spec/gem_example.rb
spec/ruby_example.rb
spec/schemas/gem.yml
spec/schemas/ruby.yml
spec/spec_helper.rb

Validate advisories through schemas

---

gems/haml/CVE-2017-1002201.yml

This advisory was apparently published by snyk in 2017, though the publish date on NIST is 10/15/2019. I was made aware of it by Github security scanning which has recently picked this up as well.

Add missing CVE-2017-1002201 for haml

---

gems/brakeman/CVE-2019-18409.yml

Hi, 
Please consider this PR for the brakeman gems.
The brakeman's security team has published a fix in the version 4.7.1.
The gem ruby_parser-legacy is statically include in brakeman when the gem is builded.
https://github.com/zenspider/ruby_parser-legacy/issues/1

CVE-2019-18409.yml for brakeman

---

gems/ruby_parser-legacy/CVE-2019-18409.yml

Hi,
Please consider this PR for the CVE-2019-18409.
https://nvd.nist.gov/vuln/detail/CVE-2019-18409.
Thanks

CVE-2019-18409.yml for ruby_parser-legacy

---

gems/nokogiri/CVE-2020-7595.yml

For https://github.com/sparklemotion/nokogiri/issues/1992

Add CVE-2020-7595 for nokogiri

---

gems/puma/CVE-2020-5247.yml

NB: Patched versions are an extra point release higher than the CVE is declared against, as a bug was fixed against the immediate release and a further vector (early hints) was closed.

Add CVE-2020-5247 against puma, fixing #435

---

gems/rake/CVE-2020-8130.yml

https://github.com/advisories/GHSA-jppv-gw3r-w3q8
> There is an OS command injection vulnerability in Rake (a ruby make-like utility) < 12.3.3 in Rake::FileList when supplying a filename that begins with the pipe character `|`.

Add CVE-2020-8130 for Rake

---

gems/fileutils/CVE-2013-2516.yml
gems/lynx/CVE-2014-5002.yml
gems/mapbox-rails/OSVDB-129854.yml
gems/mapbox-rails/OSVDB-132871.yml

Some vulnerabilities have been patched in new releases. This avoids false positives.
Regarding `mapbox-rails` the versions are from the upstream JS library, but the gem versions match the upstream JS ones.

Update vulns with patched versions

---

gems/passenger/CVE-2018-12026.yml

I add CVE-2018-12026.yml.
I used the following articles as a reference when I wrote CVE-2018-12026.yml.
https://blog.phusion.nl/2018/06/12/passenger-5-3-2-various-security-fixes/
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-12026
https://nvd.nist.gov/vuln/detail/CVE-2018-12026

Add CVE-2018-12026 for passenger.

---

gems/pghero/CVE-2020-16253.yml

For https://github.com/ankane/pghero/issues/330

Added CVE-2020-16253 for pghero

---

gems/kramdown/CVE-2020-14001.yml

https://github.com/advisories/GHSA-mqm2-cgpr-p4m6
> The kramdown gem before 2.3.0 for Ruby processes the template option
> inside Kramdown documents by default, which allows unintended read
> access (such as template="/etc/passwd") or unintended embedded Ruby
> code execution (such as a string that begins with
> template="string://<%= `). NOTE: kramdown is used in Jekyll, GitLab
> Pages, GitHub Pages, and Thredded Forum.

Add CVE-2020-14001 for Kramdown

---

gems/fileutils/OSVDB-90715.yml
gems/fileutils/OSVDB-90716.yml
gems/fileutils/OSVDB-90718.yml

As a followup to my discussion with Hiroshi Shibata, maintainer of the https://rubygems.org/gems/fileutils gem:
The following reports are no longer valid and completely misleading, causing the users of those to get false alarms in case fileutils ends up in the gemfile.

Remove misleading fileutils OSVDB reports

---

gems/activerecord-session_store/CVE-2019-25025.yml

I just merged https://github.com/rails/activerecord-session_store/pull/151 and release [version 2.0.0](https://github.com/rails/activerecord-session_store/releases/tag/v2.0.0) which contains a fix and mitigation. Users are now advised to upgrade to version 2.0.0 or later.
Please let me know if this patch is ok, or if there's anything else I should fix. Thank you very much.

Update activerecord-session_store advisory info

---

gems/rexml/CVE-2021-28965.yml

For [REXML](https://www.ruby-lang.org/en/news/2021/04/05/xml-round-trip-vulnerability-in-rexml-cve-2021-28965/)

Add CVE-2021-28965 for REXML

---

gems/tmpdir/CVE-2021-28966.yml

Here is the modified commit on the repository side of gem. https://github.com/ruby/tmpdir/commit/adf294bc2d10cd223aa3ca488079ec313032c07b

Add CVE-2021-28966 for tmpdir

---

gems/puma/CVE-2021-29509.yml

It seems that this cannot be found by `sync_github_advisories` so I added it manually. Is this something expected or I missed something? Thanks!

Add CVE-2021-29509 for puma

---

gems/bundler/CVE-2020-36327.yml

PR to add the CVE for implicit dependency confusion.
I have two questions about this:
1) Is it correct to put 2.2.10 in the `unaffected_versions` section? Technically that version was patched (and the patch was rolled back in 2.2.11), so `patched_versions` seems more appropriate. However, if I put it there then a test fails:
```
Failures:
1) gems /Users/zofrex/Code/ruby/ruby-advisory-db/spec/../gems/bundler/CVE-2020-36327.yml versions assumes that future versions will be patched
Failure/Error: expect(versions.last.match(/^>=|^>/)).to be_truthy
expected: truthy value
got: nil
Shared Example Group: "Gem Advisory" called from ./spec/advisories_spec.rb:8
```
2) I wrote a blog post about this vulnerability, explaining it in more detail and outlining some possible mitigations. Would it be OK to …

Add Bundler CVE-2020-36327

---

gems/actionpack/CVE-2021-22881.yml

I missed one in #477. Mark CVE-2021-22881 as patched in Rails 6.0.4.

Mark Rails ~> 6.0.4 as patched

---

gems/bindata/CVE-2021-32823.yml

This relates to this conversation: https://github.com/rubysec/ruby-advisory-db/issues/476
This adds a new advisory for `bindata` for CVE-2021-32823 / https://github.com/advisories/GHSA-hj56-84jw-67h6.
CC @kuahyeow @reedloden @postmodern

add CVE-2021-32823 for bindata

---

lib/github_advisory_sync.rb

I came across some vulnerabilities that were missing cvss scores present on Github, so I wanted to update the github sync script to pull down those values automatically. I broke the change into three commits:
1. The first commit is a refactor of the github sync to query vulnerabilities instead of advisories. This was done because I noticed that the number of queries made to pull down all of the vulnerabilities seemed too high (43 when I first ran it), and it turned out that it was getting advisories for all ecosystems and not just ruby. After the refactor, it is able to pull all of the ruby vulnerabilities and advisories in 7 requests.
2. The second commit is the change that adds missing cvss scores if the score is present on Github.
3. The third is the result of running the script, …

add missing cvss_v3 scores during github sync

---

gems/addressable/CVE-2021-32740.yml

Add GHSA-jxhc-q857-3j6g / CVE-2021-32740 for `addressable` advisory.
- https://github.com/advisories/GHSA-jxhc-q857-3j6g
- https://nvd.nist.gov/vuln/detail/CVE-2021-32740
- https://github.com/sporkmonger/addressable/security/advisories/GHSA-jxhc-q857-3j6g

Add GHSA-jxhc-q857-3j6g / CVE-2021-32740

---

gems/sidekiq/CVE-2022-23837.yml

PR that backports: https://github.com/mperham/sidekiq/pull/5157
Rubygems release: https://rubygems.org/gems/sidekiq/versions/5.2.10

Sidekiq version 5.2.10 also addresses CVE-2022-23837

---

rubies/ruby/CVE-2022-28738.yml
rubies/ruby/CVE-2022-28739.yml

Those 2 new CVEs are impacting ruby directly and are not in the github registry of CVEs (hence are not synced here):
* https://www.ruby-lang.org/en/news/2022/04/12/buffer-overrun-in-string-to-float-cve-2022-28739/
* https://www.ruby-lang.org/en/news/2022/04/12/double-free-in-regexp-compilation-cve-2022-28738/

Add latest ruby CVEs

---

gems/gibbon/CVE-2022-27311.yml

This reported CVE's fix has now been merged into gibbon, and released as 3.4.4. I've updated the description with the github sync rake task, and included the patched version.

Update gibbon to show 3.4.4 is patched

---

gems/sinatra/CVE-2022-29970.yml

Saw this go by on the NIST feed and noticed that it's not here
https://nvd.nist.gov/vuln/detail/CVE-2022-29970
https://github.com/advisories/GHSA-qp49-3pvw-x4m5

Add missing CVSS scores for CVE-2022-29970 on sinatra

---

gems/cgi/CVE-2021-41816.yml
gems/cgi/CVE-2021-41819.yml

Add patched version for CVE-2021-41816 and CVE-2021-41819 on cgi. These are fixed in cgi 0.1.0.1 bundled with Ruby 2.7.5 or later.
- ref: https://github.com/ruby/ruby/commit/f69aeb83146be640995753667fdd6c6f157527f5

Add patched version for CVE-2021-41816 and CVE-2021-41819 on cgi

---

gems/rexml/CVE-2021-28965.yml

Similar to https://github.com/rubysec/ruby-advisory-db/pull/511.
Add patched version for CVE-2021-28965 on rexml. This is fixed in `rexml-3.1.9.1` included in Ruby `2.6.7` (https://github.com/ruby/ruby/commit/1b59a4dc76caa061355f4289d2c54d4625671735) and `rexml-3.2.3.1` included in Ruby `2.7.3` (https://github.com/ruby/ruby/commit/b59e5a64be40b93370afbb0accfcb73c4d682045).
```
$ docker run -it --rm --name ruby ruby:2.6.7 ls -l /usr/local/lib/ruby/gems/2.6.0/specifications/default/ | grep rexml
-rw-r--r-- 1 root root  2795 Jun 23  2021 rexml-3.1.9.1.gemspec
```
```
$ docker run -it --rm --name ruby ruby:2.7.3 ls -l /usr/local/lib/ruby/gems/2.7.0/specifications/default/ | grep rexml
-rw-r--r-- 1 root root  2617 Jun 23  2021 rexml-3.2.3.1.gemspec
```

Add patched version for CVE-2021-28965 on rexml

---

gems/rdoc/CVE-2021-31799.yml

Similar to https://github.com/rubysec/ruby-advisory-db/pull/511.
Add patched version for CVE-2021-31799 on rdoc. This is fixed in `rdoc-6.1.2.1` included in Ruby `2.6.8` (https://github.com/ruby/ruby/commit/fe3c49c9baeeab58304ede915b7edd18ecf360fc) and `rdoc-6.2.1.1` included in Ruby `2.7.4` (https://github.com/ruby/ruby/commit/483f303d02e768b69e476e0b9be4ab2f26389522, https://github.com/ruby/ruby/commit/9e0e99023ddef9c0ea80dfc7f0b6924c1be95d03).
```
$ docker run -it --rm --name ruby ruby:2.6.8 ls -l /usr/local/lib/ruby/gems/2.6.0/specifications/default | grep rdoc
-rw-r--r-- 1 root root  6422 Nov 17  2021 rdoc-6.1.2.1.gemspec
```
```
$ docker run -it --rm --name ruby ruby:2.7.4 ls -l /usr/local/lib/ruby/gems/2.7.0/specifications/default | grep rdoc
-rw-r--r-- 1 root root  5309 Nov 17 …
```

Add patched version for  CVE-2021-31799 on rdoc

---

gems/activerecord/CVE-2022-32224.yml

The file for this CVE contains an Active Record config option but with `active_storage` instead of `active_record`. This doesn't work, but does work when corrected to `active_record`. I assume this was just a typo so have corrected it.

Fix unsafe yaml config option in CVE-2022-32224

---

rubies/jruby/CVE-2022-25857.yml

Hello, there is a CVE for jruby, I'm not 100% sure of how I did the report as it is a transitive dependency but in the end it gets bundled into the jruby which is available for download.

Jruby CVE-2022-25857

---

gems/pdfkit/CVE-2022-25765.yml

Hi, it's look like [CVE-2022-25765](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25765) was fixed in [0.8.7v](https://github.com/pdfkit/pdfkit/releases).
closes #517

add patched_versions for CVE-2022-25765

---

gems/nokogiri/GHSA-2qc6-mcvw-92cw.yml

GHSA-2qc6-mcvw-92cw is reported to be fixed by 1.13.9+, not 1.13.19.

Fix patched version for nokogiri (GHSA-2qc6-mcvw-92cw)

---

rubies/ruby/CVE-2021-33621.yml

Add latest ruby cve: 
- https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-0-5-released/
- https://www.ruby-lang.org/en/news/2022/11/22/http-response-splitting-in-cgi-cve-2021-33621/

Ruby: CVE-2021-33621

---

README.md
Rakefile
lib/github_advisory_sync.rb

As a gem maintainer, when I want to add an advisory to the database I either have to start from scratch and write a YAML file by hand, or else run the task to sync the entire database which will create a number of files for gems that I don't maintain and then need to `git clean`.
To make this workflow a bit easier for gem maintainers, this PR adds the ability to pass a single gem name to the rake task, e.g.:
```
rake sync_github_advisories[nokogiri]
```
The output will be something like:
```
Getting page 1 of GitHub Vulnerabilities
Executing GraphQL request: RUBYGEM_VULNERABILITIES_WITH_GITHUB_ADVISORIES. Request variables:
---
first: 100
gem_name: nokogiri
Initializing GitHub API connection to URL: https://api.github.com/graphql
Got response code: 200
Retrieved 24 Vulnerabilities from …
```

feat: allow the sync task to run for just a single gem

---

gems/nokogiri/CVE-2017-18258.yml
gems/nokogiri/CVE-2022-23476.yml

I noticed that the sync task was pulling in an additional GHSA that was not added by the nokogiri maintainers, https://github.com/advisories/GHSA-882p-jqgm-f45g for CVE-2017-18258. This PR backfills that vulnerability.
Also, rename gems/nokogiri/GHSA-qv4q-mr5r-qprj.yml to gems/nokogiri/CVE-2022-23476.yml to reflect the filename convention used by the sync task.
gems/nokogiri is now up to date with github's advisory database.

Backfill old nokogiri vulnerability report

---

gems/loofah/CVE-2022-23514.yml
gems/loofah/CVE-2022-23515.yml
gems/loofah/CVE-2022-23516.yml
gems/rails-html-sanitizer/CVE-2022-23517.yml
gems/rails-html-sanitizer/CVE-2022-23518.yml
gems/rails-html-sanitizer/CVE-2022-23519.yml
gems/rails-html-sanitizer/CVE-2022-23520.yml

Per comments at #531, remove credits and use `related` for references. Also remove redundant CVE information from descriptions.

fix: remove credits and use `related` for references

---

gems/git/CVE-2022-46648.yml

This CVE is reserved but not public yet, but the vulnerability has been fixed via a pull request and version 1.13.0 of the git gem has been released.
The only other information I could find on CVE-2022-46648 are:
* https://github.com/ruby-git/ruby-git/pull/602/files
* https://jvn.jp/jp/JVN16765254/index.html
* https://www.cybersecurity-help.cz/vdb/SB2023010501
* Note, their vulnerable version range is incorrect. I checked the version tags for ruby-git, and `eval()` was added in 1.2.0. Versions prior to 1.2.0 do not have the `eval()`.
https://github.com/ruby-git/ruby-git/commit/ee90922f3da3f67ef19853a0759c1d09860fe3b3

Added CVE-2022-46648.

---

gems/actionpack/CVE-2023-22792.yml
gems/actionpack/CVE-2023-22795.yml
gems/activerecord/CVE-2022-44566.yml
gems/activesupport/CVE-2023-22796.yml

Rails LTS should be included.
- https://makandracards.com/railslts/508019-rails-5-2-lts-changelog#section-jul-21st-2022-version-5-2-8-15

Consider Rails LTS 5.2.8.15

---

gems/rack/CVE-2023-27530.yml

Hello,
There is this new CVE for rack that has been reported some days ago: https://discuss.rubyonrails.org/t/cve-2023-27530-possible-dos-vulnerability-in-multipart-mime-parsing/82388

Added CVE-2023-27530 for rack

---

gems/activesupport/CVE-2023-28120.yml

Hello
A possible XSS vulnerability in ActiveSupport was recently discovered. 
The CVE identifier CVE-2023-28120 has been reserved: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28120

Add CVE-2023-28120 for ActiveSupport

---

gems/rack/CVE-2023-27539.yml

Hello,
There is this new CVE for rack that has been reported some days ago: https://discuss.rubyonrails.org/t/cve-2023-27539-possible-denial-of-service-vulnerability-in-racks-header-parsing/82466

Added CVE-2023-27539 for rack

---

gems/karo/CVE-2014-10075.yml

Removed gems/karo/CVE-2014-10075.yml "patched_versions" value until more information is known.

Removed gems/karo/CVE-2014-10075.yml "patched_versions" value

---

gems/time/CVE-2023-28756.yml

The **sync_github_advisories** added **cvss_v3** line to 1 file (gems/time/CVE-2023-28756.yml).

sync_github_advisories script added cvss_v3 line

---

gems/bootstrap/CVE-2018-14042.yml

Advisory for gems/bootstrap/CVE-2018-14042.yml
* Only one left dated 2015 to present 
* Result of  lib/github_advisory_sync.rb run + post processor + manual "patched_versions" field
* Clean yamllint and rake runs

Advisory for gems/bootstrap/CVE-2018-14042.yml

---

gems/bootstrap/CVE-2018-14042.yml
gems/facter/CVE-2014-3248.yml
gems/hiera/CVE-2014-3248.yml
gems/mcollective-client/CVE-2014-3248.yml
gems/puppet/CVE-2014-3248.yml

Adding four advisories (files) based on CVE-2014-3248 advisory.
* These files were imported using "lib/github_advisory_sync.rb" script.
* Only edit was making 2-line title into 1.
* Checked "yamllint" (clean) and ran "rake" (clean).

[GHSA SYNC2] Adding four advisories based on CVE-2014-3248 advisory

---

rubies/mruby/CVE-2021-46023.yml
rubies/mruby/CVE-2022-1934.yml

Two GHSA-based mruby advisories.
* One with huntr.dev data; one without  huntr.dev data.
* 37 more mruby advisories to go after these two.

Two GHSA-based mruby advisories: One with huntr.dev data; one without

---

rubies/mruby/CVE-2021-4110.yml
rubies/mruby/CVE-2021-4188.yml
rubies/mruby/CVE-2022-0080.yml
rubies/mruby/CVE-2022-0240.yml
rubies/mruby/CVE-2022-0326.yml
rubies/mruby/CVE-2022-0481.yml
rubies/mruby/CVE-2022-0525.yml
rubies/mruby/CVE-2022-0570.yml
rubies/mruby/CVE-2022-0614.yml
rubies/mruby/CVE-2022-0623.yml
rubies/mruby/CVE-2022-0630.yml
rubies/mruby/CVE-2022-0631.yml
rubies/mruby/CVE-2022-0632.yml
rubies/mruby/CVE-2022-0717.yml
rubies/mruby/CVE-2022-0890.yml
rubies/mruby/CVE-2022-1071.yml
rubies/mruby/CVE-2022-1106.yml
rubies/mruby/CVE-2022-1201.yml
rubies/mruby/CVE-2022-1212.yml
rubies/mruby/CVE-2022-1276.yml
rubies/mruby/CVE-2022-1286.yml
rubies/mruby/CVE-2022-1427.yml

Adding the remaining 18 GHSA-based mruby huntr.dev advisories.
They are all similar (between 19-22 lines per file).
yamllint and "rake" are green.

Adding the remaining 18 GHSA-based mruby huntr.dev advisories

---

rubies/mruby/CVE-2017-9527.yml
rubies/mruby/CVE-2018-10191.yml
rubies/mruby/CVE-2018-10199.yml
rubies/mruby/CVE-2018-11743.yml
rubies/mruby/CVE-2018-12247.yml
rubies/mruby/CVE-2018-12248.yml
rubies/mruby/CVE-2018-12249.yml
rubies/mruby/CVE-2018-14337.yml
rubies/mruby/CVE-2020-15866.yml
rubies/mruby/CVE-2020-6838.yml
rubies/mruby/CVE-2020-6839.yml
rubies/mruby/CVE-2020-6840.yml

Adding 12 GHSA-based mruby non-huntr.dev advisories
yamllint and "rake" are green.

Adding 12 GHSA-based mruby non-huntr.dev advisories

---

gems/actionview/CVE-2016-0752.yml
gems/actionview/CVE-2016-2097.yml
gems/actionview/CVE-2016-6316.yml
gems/audited/GHSA-hjp3-5g2q-7jww.yml
gems/govuk_tech_docs/GHSA-x2xw-hw8g-6773.yml
gems/kitchen-terraform/CVE-2023-30618.yml
gems/pay/CVE-2023-30614.yml
gems/sha3/CVE-2022-37454.yml
gems/sidekiq/CVE-2023-1892.yml
gems/uri/CVE-2023-28755.yml

6 new and 1 modified 2015+ GHSA-sync'ed files
* Ran the unchanged "lib/sync_github_advisories" to get the most recent files in the query.
* Did minor reformatting (line wrapping) but no new content.
* Ran "yamllint" and "rake" (both clean/green).

6 new and 1 modified 2015+ GHSA-sync'ed files

---

rubies/ruby/CVE-2006-3694.yml

Found another ruby CVE advisory from 2006.
Built the file, ran "yamllint" (green) and "rake" (green).
In NVD link, saw only 1.8.2, 1.8.3, and 1.8.4 mentioned.

One more early ruby CVE advisory

---

spec/schemas/ruby.yml

Found that the ruby.yml schema did not match the updated README file so fixed it.

Updated ruby.yml schema to match README file

---

gems/facter/CVE-2015-1426.yml
gems/kafo/CVE-2014-0135.yml
gems/logstash-core/CVE-2015-5378.yml
gems/logstash-core/CVE-2015-5619.yml
gems/puppet/CVE-2014-3248.yml
gems/spina/CVE-2015-4619.yml

Updated 3 and added 3 SRC:CLR advisories with CVE values from issue #238.
* For the existing advisories, I added the updated SRC:CLR URL since SourceClear was purchased by Veracode.
* For the brand new advisories, I added new files along with the updated SRC:CLR URL.
* The other 10 URL in #238 do not have a CVE number so they need a CVE before adding them.

Updated 3 and added 3 SRC:CLR advisories with CVE values from issue #238

---

gems/actionpack/CVE-2011-0446.yml
gems/activesupport/CVE-2009-3086.yml

2 more advisories resulting from reclassifying 'rails' gems to sub-rails gems.
* gems/actionpack/CVE-2011-0446.yml
* gems/activesupport/CVE-2009-3086.yml

2 more advisories resulting from reclassifying 'rails' gems to sub-rails gems

---

gems/actionpack/CVE-2014-0081.yml
gems/actionpack/CVE-2016-0752.yml
gems/actionpack/CVE-2016-2097.yml
gems/actionpack/CVE-2016-6316.yml
gems/actionview/CVE-2023-23913.yml
gems/echor/CVE-2014-1834.yml
gems/echor/CVE-2014-1835.yml
gems/kredis/CVE-2023-27531.yml
gems/nokogiri/CVE-2013-6460.yml
gems/nokogiri/CVE-2013-6461.yml
gems/nokogiri/CVE-2017-16932.yml
gems/nokogiri/CVE-2018-8048.yml
gems/nokogiri/CVE-2019-13117.yml
gems/open-uri-cached/CVE-2015-3649.yml
gems/passenger/CVE-2018-12026.yml
gems/passenger/CVE-2018-12029.yml

GHSA sync + modifies + few manual edits
After running the sync script and removing dups/etc and post-processor script and a few manual edits, the modify summary is:
* ghsa: field was added
* Single quotes changed to double quotes per local convention
* Added double quotes back if removed.
* Reorder date: field in file.

GHSA sync + modifies + few manual edits

---

gems/rwiki/CVE-2006-2582.yml

2nd GHSA rwiki advisories from 2006
* CVE-2006-2582.yml
Previous one was CVE-2006-2581.

2nd GHSA rwiki advisories from 2006

---

gems/doorkeeper/CVE-2023-34246.yml
gems/gitlab-grit/CVE-2013-4489.yml

**GSHA-sync: 1 new advisory; 1 modified**
Ran GHSA sync script plus post-processing and got:
* Added ghsa: field to 1 advisory file.
* Added brand new advisory: gems/doorkeeper/CVE-2023-34246.yml

GSHA-sync: 1 new advisory; 1 modified

---

gems/kredis/CVE-2023-27531.yml

`ooooooo_k` is a typo.
I contacted the typo of [rails](https://discuss.rubyonrails.org/t/cve-2023-27531-possible-deserialization-of-untrusted-data-vulnerability-in-kredis-json/82467#post_1) and had it corrected, but it seems that it was not reflected here.
It was said that credit is not usually included, so I deleted it.

Remove credit for CVE-2023-27531

---

lib/github_advisory_sync.rb

Change min_year from 2015 to 2000 to support more GHSA rubygem advisories.
We have be supporting these advisories for a good while but using local means.
Now we can make it permanent.
@reedloden

Change min_year from 2015 to 2000 to support more GHSA rubygem advisories

---

spec/advisory_example.rb

Added lint check to not support 'osvdb' in main url: field since it is shuttered.

Added lint check to not support 'osvdb' in main url: field

---

gems/bundler/CVE-2016-7954.yml

Added 2016 gems/bundler/CVE-2016-7954.yml advisory.
NOTE: This will flag all 1.x versions of bundler.

Added 2016 gems/bundler/CVE-2016-7954.yml advisory

---

lib/github_advisory_sync.rb

Attempt to automatically generate the `patched_versions` from the GHSA `vulnerabilities`/`firstPatchedVersion`/`identiifer` information.

Attempt to generate `patched_versions` from GHSA `firstPatchedVersion`.

---

lib/github_advisory_sync.rb

Since we added code for patched_version field, we can removed extra patched_versions yaml line.
```
"patched_versions"    => ["<FILL IN SEE BELOW>"],
```

Removed extra patched_versions yaml line

---

spec/advisory_example.rb

Added lint rule to check that OSVDB-* advisories with "ghsa:" values have filenames starting with GSHA.
To test this, add a "ghsa:" field/value to an existing OSVDB advisory and run "rake".

Add "Prefer GHSA over OSVDB filename" lint rule

---

rubies/ruby/CVE-2008-2662.yml
rubies/ruby/CVE-2008-2663.yml
rubies/ruby/CVE-2008-2725.yml

Corrected "ghsa:" values (they were duplicates) for 3 rubies/ruby advisories.

Corrected "ghsa:" values (they were duplicates) for 3 rubies/ruby advisories

---

lib/github_advisory_sync.rb

Omit `patched_versions:` if the GHSA has no patched version identifiers.

---

lib/github_advisory_sync.rb

Generate `unaffected_versions` based on the inverse of the first `vulnerableVersionRange`, iff `vulnerableVersionRange` starts with `> ` or `>= `.

Attempt to automatically generate `unaffected_versions:`

---

gems/grpc/CVE-2023-1428.yml
gems/grpc/CVE-2023-32732.yml
gems/jquery-rails/CVE-2020-23064.yml
gems/nokogiri/CVE-2019-18197.yml
gems/nokogiri/CVE-2019-5815.yml

GHSA Sync: 5 more new advisories. Used #676 code.

GHSA Sync: 5 more new advisories

---

lib/github_advisory_sync.rb

Add "jquery-rails" as a candidate to add "framework: rails" during sync script run.

Add "jquery-rails" as a candidate to add "framework: rails" during sync script run 

---

gems/sinatra/CVE-2018-11627.yml
spec/gem_advisory_example.rb

[Lint Check] Locked down unaffected_versions.last value to 6 operators [ ^<=, ^<, ^>=, ^>, ~>, ^=/ ].

[Lint Check] Locked down unaffected_versions.last value to 6 operators

---

gems/activesupport/CVE-2023-38037.yml

Add a file for the activesupport CVE.
Link: https://discuss.rubyonrails.org/t/cve-2023-38037-possible-file-disclosure-of-locally-encrypted-files/83544/1

Add cve file for activesupport

---

gems/activesupport/CVE-2023-38037.yml

GHSA Sync: Changed single quotes to double quotes and add "ghsa:" value for one advisory.

GHSA Sync: Changed single quotes to double quotes and add "ghsa:" value for one advisory

---

gems/nokogiri/CVE-2017-15412.yml

GHSA SYNC: Added cvss_v3 and ghsa fields to 1 advisory: gems/nokogiri/CVE-2017-15412.yml .

GHSA SYNC: Added cvss_v3 and ghsa fields to 1 advisory

---

gems/jquery-rails/CVE-2011-4969.yml
gems/jquery-rails/CVE-2016-10707.yml
gems/jquery-rails/CVE-2020-11022.yml
gems/jquery-ui-rails/CVE-2021-41182.yml
gems/jquery-ui-rails/CVE-2021-41183.yml
gems/jquery-ui-rails/CVE-2021-41184.yml

GHSA Sync: Added 6 brand new jquery-related advisories.

GHSA Sync: Added 6 brand new jquery-related advisories

---

gems/twitter-bootstrap-rails/CVE-2019-8331.yml

CVE-2019-8331 has already been reported for the `bootstrap` and `bootstrap-sass` gems, but the `twitter-bootstrap-rails` gem is still affected, since it includes the vulnerable 3.3.6 version.
I'm not sure if it's appropriate for me to tell users that "hey, there's this other version of the bootstrap gem that's actually maintained by the original developer, and until this gem is fixed you should use it instead". I have done it anyway; please let me know if that needs to be changed.

Add CVE-2019-8331 for `twitter-bootstrap-rails`

---

gems/pubnub/CVE-2023-26154.yml

GHSA Sync: 1 brand new advisory: gems/pubnub/CVE-2023-26154.yml 
Added tag URL for corrected version.

GHSA Sync: 1 brand new advisory

---

gems/activeadmin/CVE-2023-50448.yml

GHSA Sync: 1 brand new advisory: gems/activeadmin/CVE-2023-50448.yml

GHSA Sync: 1 brand new advisory: gems/activeadmin/CVE-2023-50448.yml

---

gems/handlebars-source/CVE-2021-23369.yml
gems/handlebars-source/CVE-2021-23383.yml

The `handlebars-source` gem (wraps the JS library [handlebars](https://github.com/handlebars-lang/handlebars.js)) has had about a dozen vulnerabilities over the years (see: https://github.com/advisories?query=handlebars and https://security.snyk.io/package/npm/handlebars). I've chosen to only add advisories for the most recent two of these, since handlebars v 4.7.7 will also fix the rest. I hope that's OK.

add CVE-2021-23369 and CVE-2021-23383 for `handlebars-source`

---

gems/avo/CVE-2024-22411.yml

github advisory (https://github.com/advisories/GHSA-g8vp-2v5p-9qfh) was updated to include more vulnerable releases in the 3.x branch and a fixed 2.x version.
This PR aligns ruby-advisory-db with github advisory

Update CVE-2024-22411 to align with updated github advisory

---

gems/webrick/CVE-2008-4310.yml

GHSA SYNC: Another brand new advisory: gems/webrick/CVE-2008-4310.yml

GHSA SYNC: Another brand new advisory

---

gems/jquery-ui-rails/CVE-2021-41182.yml
gems/jquery-ui-rails/CVE-2021-41183.yml
gems/jquery-ui-rails/CVE-2021-41184.yml

The Ruby gem `jquery-ui-rails` relies on the NPM package `jquery-ui` according [to this table](https://github.com/jquery-ui-rails/jquery-ui-rails/blob/master/VERSIONS.md).
It appears that the patched versions in `CVE-2021-41182`, `CVE-2021-41183`, and `CVE-2021-41184` are based on the NPM package `jquery-ui`. Therefore, this PR addresses the issue by adjusting them to reflect the versioning of `jquery-ui-rails`.

Update CVE-2021-41182, CVE-2021-41183, CVE-2021-41184

---

gems/activestorage/CVE-2024-26144.yml

The gem was incorrectly specified and has been corrected. (95316e8819722457f564263ee7fb448fbaee5063)

Moved to activestorage.

---

gems/rack-cors/CVE-2024-27456.yml

Updated the advisory for CVE-2024-27456 to include the unaffected versions.

GHSA Add unaffected_versions to CVE-2024-27456

---

gems/rack-cors/CVE-2024-27456.yml

The CVE was fixed in 2.0.2, see https://github.com/cyu/rack-cors/issues/274

Mark rack-cors 2.0.2 as resolving CVE-2024-27456

---

gems/nokogiri/GHSA-vcc3-rw6f-jv97.yml
gems/rotp/CVE-2024-28862.yml

GHSA SYNC: 2 brand new advisories:
* gems/nokogiri/GHSA-vcc3-rw6f-jv97.yml
* gems/rotp/CVE-2024-28862.yml

GHSA SYNC: 2 brand new advisories

---

gems/actiontext/CVE-2024-34341.yml

Amends #784 (earlier fix to #783) to match affected versions with that officially documented at https://discuss.rubyonrails.org/t/xss-vulnerabilities-in-trix-editor/85803
I can't find any source for the assertion that < 7.0 is vulnerable in contradiction to the Rails teams' assertions, so suggest removing it.

Correct affected versions for CVE-2024-34341

---

gems/avo/CVE-2023-34102.yml
gems/avo/CVE-2023-34103.yml
gems/avo/CVE-2024-22191.yml
gems/yard/CVE-2024-27285.yml
spec/advisory_example.rb

Added Rspec lint check to prevent PoC sections inside description field.
Also removed existing description/PoC subsections.from 4 advisories.

Added Rspec lint check to prevent PoC sections inside description field

---

gems/rack/CVE-2024-39316.yml

GHSA SYNC: One brand new advisory: gems/rack/CVE-2024-39316.yml

GHSA SYNC: One brand new advisory

---

gems/decidim-admin/CVE-2024-27095.yml
gems/decidim/CVE-2024-27090.yml
gems/decidim/CVE-2024-32469.yml
gems/stringio/CVE-2024-27280.yml

GHSA SYNC: 3 brand new advisories:
* gems/decidim-admin/CVE-2024-27095.yml
* gems/decidim/CVE-2024-27090.yml
* gems/decidim/CVE-2024-32469.yml

GHSA SYNC: 3 brand new advisories

---

gems/rexml/CVE-2024-39908.yml

GHSA SYNC adds ghsa: and cvss_v3 fields to yesterday's advisory: gems/rexml/CVE-2024-39908.yml

GHSA SYNC adds ghsa: and cvss_v3 fields to yesterday's advisory

---

gems/bootstrap-sass/CVE-2016-10735.yml
gems/bootstrap-sass/CVE-2018-14042.yml
gems/bootstrap-sass/CVE-2018-20676.yml
gems/bootstrap-sass/CVE-2018-20677.yml
gems/bootstrap-sass/CVE-2024-6484.yml
gems/bootstrap/CVE-2016-10735.yml
gems/bootstrap/CVE-2018-20676.yml
gems/bootstrap/CVE-2018-20677.yml
gems/bootstrap/CVE-2024-6484.yml
gems/bootstrap/CVE-2024-6531.yml
gems/rexml/CVE-2024-41123.yml

GHSA SYNC: 3 modified and 8 brand new advisories:
Modified:
* gems/bootstrap-sass/CVE-2016-10735.yml
* gems/bootstrap/CVE-2016-10735.yml
* gems/rexml/CVE-2024-41123.yml
Brand New: **NOTE that several  of these CVEs were fixed privately by https://www.herodevs.com company)**
* gems/bootstrap-sass/CVE-2018-14042.yml
* gems/bootstrap-sass/CVE-2018-20676.yml
* gems/bootstrap-sass/CVE-2018-20677.yml
* gems/bootstrap-sass/CVE-2024-6484.yml
* gems/bootstrap/CVE-2018-20676.yml
* gems/bootstrap/CVE-2018-20677.yml
* gems/bootstrap/CVE-2024-6484.yml
* gems/bootstrap/CVE-2024-6531.yml

GHSA SYNC: 3 modified and 8 brand new advisories

---

gems/sequenceserver/CVE-2024-42360.yml
gems/spina/CVE-2024-7106.yml

GSHA SYNC: 2 brand new advisories:
* gems/sequenceserver/CVE-2024-42360.yml
* gems/spina/CVE-2024-7106.yml

GSHA SYNC: 2 brand new advisories

---

gems/fugit/CVE-2024-43380.yml

GSHA SYNC: 1 brand new advisory: gems/fugit/CVE-2024-43380.yml

GSHA SYNC: 1 brand new advisory

---

gems/rdoc/CVE-2024-27281.yml

GHSA SYNC: Added cvss_v3 field to 1 advisory: gems/rdoc/CVE-2024-27281.yml

GHSA SYNC: Added cvss_v3 field to 1 advisory

---

gems/omniauth-saml/CVE-2024-45409.yml
gems/ruby-saml/CVE-2024-45409.yml

Add CVE-2024-45409 for ruby-saml and omniauth-saml

---

gems/webrick/CVE-2024-47220.yml

GHSA SYNC: 1 brand new advisory: gems/webrick/CVE-2024-47220.yml

GHSA SYNC: 1 brand new advisory (pm)

---

gems/actionmailer/CVE-2024-47889.yml
gems/actionpack/CVE-2024-41128.yml
gems/actionpack/CVE-2024-47887.yml
gems/actiontext/CVE-2024-47888.yml

With new version of Rails (7.1.5), false alarms are now ringing bells because of too restrictive version specified in the "patched versions" section of affected gems.
The change updates the version range, so that `7.1.5` doesn't fail the validation.
Failures with the existing version range:
```
Name: actionmailer
Version: 7.1.5
CVE: CVE-2024-47889
GHSA: GHSA-h47h-mwp9-c6q6
Criticality: Unknown
URL: https://github.com/rails/rails/security/advisories/GHSA-h47h-mwp9-c6q6
Title: Possible ReDoS vulnerability in block_format in Action Mailer
Solution: update to '~> 6.1.7.9', '~> 7.0.8.5', '~> 7.1.4.1', '>= 7.2.1.1'
Name: actionpack
Version: 7.1.5
CVE: CVE-2024-41128
GHSA: GHSA-x76w-6vjr-8xgj
Criticality: Unknown
URL: https://github.com/rails/rails/security/advisories/GHSA-x76w-6vjr-8xgj
Title: …
```

Update patched versions to include 7.1.5 for CVE-2024-47889, CVE-2024-47888, CVE-2024-47887, CVE-2024-41128

---

gems/sinatra/CVE-2024-21510.yml

CVE 2024-21510 should be patched with version `4.1.0`.
See the [CHANGELOG](https://github.com/sinatra/sinatra/blob/main/CHANGELOG.md) for details and [the advisory-database](https://github.com/github/advisory-database/pull/5018).

Added patched_versions to CVE 2024-21510

---

gems/rails-html-sanitizer/CVE-2024-53985.yml
gems/rails-html-sanitizer/CVE-2024-53986.yml
gems/rails-html-sanitizer/CVE-2024-53987.yml
gems/rails-html-sanitizer/CVE-2024-53988.yml
gems/rails-html-sanitizer/CVE-2024-53989.yml

GHSA SYNC: 5 brand new advisories:
* gems/rails-html-sanitizer/CVE-2024-53985.yml
* gems/rails-html-sanitizer/CVE-2024-53986.yml
* gems/rails-html-sanitizer/CVE-2024-53987.yml
* gems/rails-html-sanitizer/CVE-2024-53988.yml
* gems/rails-html-sanitizer/CVE-2024-53989.yml
Note: Appears to be very similar.

GHSA SYNC: 5 brand new advisories

---

gems/actionpack/CVE-2023-28362.yml
gems/activesupport/CVE-2023-28120.yml
gems/activesupport/CVE-2023-38037.yml
gems/kredis/CVE-2023-27531.yml

GHSA SYNC: 4 modified new advisories
* gems/actionpack/CVE-2023-28362.yml
* gems/activesupport/CVE-2023-28120.yml
* gems/activesupport/CVE-2023-38037.yml
* gems/kredis/CVE-2023-27531.yml

GHSA SYNC: 4 modified new advisories

---

gems/actionpack/CVE-2024-54133.yml
gems/net-imap/CVE-2025-25186.yml
gems/rack/CVE-2025-25184.yml
gems/rails-html-sanitizer/CVE-2024-53986.yml
gems/rails-html-sanitizer/CVE-2024-53987.yml
gems/rails-html-sanitizer/CVE-2024-53988.yml
gems/rails-html-sanitizer/CVE-2024-53989.yml

6 enhanced advisories; 1 brand new advisory:
Add 1 or 2 hackerone or  ruby-lang.org references to:
* gems/actionpack/CVE-2024-54133.yml
* gems/net-imap/CVE-2025-25186.yml
* gems/rails-html-sanitizer/CVE-2024-53986.yml
* gems/rails-html-sanitizer/CVE-2024-53987.yml
* gems/rails-html-sanitizer/CVE-2024-53988.yml
* gems/rails-html-sanitizer/CVE-2024-53989.yml
Brand new:
* gems/rack/CVE-2025-25184.yml

6 enhanced advisories; 1 brand new advisory

---

README.md
gems/actionpack/CVE-2023-22792.yml
gems/actionpack/CVE-2023-22795.yml
gems/activerecord/CVE-2022-44566.yml
gems/activesupport/CVE-2023-22796.yml

We (the Rails LTS team) noticed that some CVEs are marked as fixed by Rails LTS in the ruby-advisory-db. While we appreciate and are grateful for the effort, we would prefer not to list our commercial versions in the official database as fixed versions.
Currently, we do not have the capacity to actively monitor all versions listed in the ruby-advisory-db, verify their accuracy, and ensure correctness. Additionally, some fixes require extra context or additional information that may not be adequately reflected in the database. Most Rails LTS versions are a commercial offering, and we maintain a comprehensive list of all CVEs we have addressed—along with the necessary details—at https://makandracards.com/railslts/474590-list-cves-addressed-rails-lts. Every Rails LTS customer also receives a …

Remove Rails LTS versions

---

gems/rexml/CVE-2024-43398.yml

* GHSA SYNC: Added hackerone reference to 1 existing advisory: gems/rexml/CVE-2024-43398.yml

GHSA SYNC: Added hackerone reference to 1 existing advisory

---

gems/cgi/CVE-2025-27219.yml
gems/cgi/CVE-2025-27220.yml
gems/uri/CVE-2025-27221.yml

3 brand new non-GHSA advisories
* gems/cgi/CVE-2025-27219.yml
* gems/cgi/CVE-2025-27220.yml
* gems/uri/CVE-2025-27221.yml

3 brand new non-GHSA advisories

---

gems/rack/CVE-2025-27610.yml

- new file: gems/rack/CVE-2025-27610.yml

GHSA SYNC[rack]: 1 brand new advisory: CVE-2025-27610

---

gems/ruby-saml/CVE-2025-25291.yml
gems/ruby-saml/CVE-2025-25292.yml
gems/ruby-saml/CVE-2025-25293.yml

Added 3 new advisories of CVEs affecting the `ruby-saml` gem

GHSA SYNC[ruby-saml]: 3 new advisories: CVE 2025-25291, CVE 2025-25292 and CVE 2025-25293

---

gems/net-imap/CVE-2025-25186.yml

GHSA SYNC: Add hackerone reference to 1 advisory: gems/net-imap/CVE-2025-25186.yml

GHSA SYNC: Add hackerone reference to 1 advisory

---

gems/activestorage/CVE-2024-26144.yml
gems/cgi/CVE-2025-27219.yml
gems/net-imap/CVE-2025-25186.yml
gems/net-imap/CVE-2025-43857.yml
gems/rexml/CVE-2024-43398.yml

GHSA SYNC: 1 brand new and 4 modified advisories:
* New: gems/net-imap/CVE-2025-43857.yml
* Modified (mostly additional hackerone references)
* gems/rexml/CVE-2024-43398.yml
* gems/cgi/CVE-2025-27219.yml
* gems/activestorage/CVE-2024-26144.yml
* gems/net-imap/CVE-2025-25186.yml

GHSA SYNC: 1 brand new and 4 modified advisories

---

gems/resolv/CVE-2025-24294.yml

New ruby-lang-based advisory: gems/resolv/CVE-2025-24294

New ruby-lang.com-based advisory

---

gems/measured/GHSA-29g5-m8v7-v564.yml
gems/resolv/CVE-2025-24294.yml

GHSA SYNC: Updated 2 fields in 1 existing advisory + 1 brand new advisory
* gems/resolv/CVE-2025-24294.yml
* gems/measured/GHSA-29g5-m8v7-v564.yml

GHSA SYNC: Updated 2 fields in 1 existing advisory + 1 brand new advisory

---

gems/lodash-rails/CVE-2018-16487.yml
gems/lodash-rails/CVE-2018-3721.yml
gems/lodash-rails/CVE-2019-1010266.yml
gems/lodash-rails/CVE-2019-10744.yml
gems/lodash-rails/CVE-2020-28500.yml
gems/lodash-rails/CVE-2020-8203.yml
gems/lodash-rails/CVE-2021-23337.yml

GHSA SYNC: 7 brand new advisories:
* gems/lodash-rails/CVE-2018-16487.yml
* gems/lodash-rails/CVE-2018-3721.yml
* gems/lodash-rails/CVE-2019-1010266.yml
* gems/lodash-rails/CVE-2019-10744.yml
* gems/lodash-rails/CVE-2020-28500.yml
* gems/lodash-rails/CVE-2020-8203.yml
* gems/lodash-rails/CVE-2021-23337.yml

GHSA SYNC: 7 brand new advisories

---

gems/lodash-rails/CVE-2019-1010266.yml

GHSA SYNC: cvss_v3 field and value was added
* For  gems/lodash-rails/CVE-2019-1010266.yml

GHSA SYNC: cvss_v3 field and value was added

---

gems/ckeditor/CVE-2021-26271.yml

Fixed indentation of the `related: url:` for CVE-2021-2671.

Fixed linting for CVE-2021-2671
